"""Reference-trajectory tracker support for the Level3 v54 lane."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Self

import gymnasium as gym
import numpy as np
import torch
import torch.nn as nn
from drone_models.core import load_params
from gymnasium import spaces
from gymnasium.wrappers.jax_to_numpy import JaxToNumpy
from torch import Tensor
from torch.distributions.normal import Normal

from lsy_drone_racing.utils import load_config

REFERENCE_TRACKER_LAYOUT = "level3_reference_tracker_v1"
REFERENCE_TRACKER_POLICY_ARCH = "mlp_2x256_tanh"
REFERENCE_TRACKER_HISTORY = 2
REFERENCE_TRACKER_HISTORY_DIM = 7
REFERENCE_TRACKER_PHASES = (
    "hover",
    "cruise",
    "slowdown",
    "align",
    "cross",
    "recover",
)
REFERENCE_TRACKER_OBS_DIM = 65


@dataclass(frozen=True)
class ReferenceFrame:
    """Local trajectory target generated by the upper planner."""

    phase: str
    phase_id: int
    target_gate: int
    current_point: np.ndarray
    next_point: np.ndarray
    lookahead_point: np.ndarray
    desired_velocity: np.ndarray
    desired_heading: np.ndarray
    desired_speed: float
    gate_local_position: np.ndarray
    aperture_yz: np.ndarray
    obstacle_relative: np.ndarray
    obstacle_distance: float
    obstacle_detected: float


@dataclass
class TrackerMemory:
    """Per-episode memory used by the observation builder."""

    history: list[np.ndarray]
    last_action_norm: np.ndarray

    @classmethod
    def from_observation(
        cls,
        obs: dict[str, Any],
        n_history: int = REFERENCE_TRACKER_HISTORY,
    ) -> Self:
        """Initialize tracker memory from the first raw environment observation."""
        basic = tracker_history_row(obs)
        return cls(
            history=[basic.copy() for _ in range(n_history)],
            last_action_norm=np.zeros(4, dtype=np.float32),
        )

    def update(self, obs: dict[str, Any], action_norm: np.ndarray) -> None:
        """Append one raw-observation history row and remember the latest action."""
        self.history.append(tracker_history_row(obs))
        self.history = self.history[-REFERENCE_TRACKER_HISTORY:]
        self.last_action_norm = np.clip(np.asarray(action_norm, dtype=np.float32), -1.0, 1.0)


def layer_init(layer: nn.Module, std: float = np.sqrt(2), bias_const: float = 0.0) -> nn.Module:
    """Orthogonally initialize a linear layer like the existing PPO agents."""
    torch.nn.init.orthogonal_(layer.weight, std)
    torch.nn.init.constant_(layer.bias, bias_const)
    return layer


class TrackerPPOAgent(nn.Module):
    """Small MLP PPO actor/critic for the reference-tracker observation."""

    def __init__(
        self,
        obs_dim: int = REFERENCE_TRACKER_OBS_DIM,
        action_dim: int = 4,
        hidden_dim: int = 256,
    ):
        """Build actor, critic, and learned action standard deviation."""
        super().__init__()
        self.obs_dim = int(obs_dim)
        self.action_dim = int(action_dim)
        self.hidden_dim = int(hidden_dim)
        self.critic = nn.Sequential(
            layer_init(nn.Linear(self.obs_dim, self.hidden_dim)),
            nn.Tanh(),
            layer_init(nn.Linear(self.hidden_dim, self.hidden_dim)),
            nn.Tanh(),
            layer_init(nn.Linear(self.hidden_dim, 1), std=1.0),
        )
        self.actor_mean = nn.Sequential(
            layer_init(nn.Linear(self.obs_dim, self.hidden_dim)),
            nn.Tanh(),
            layer_init(nn.Linear(self.hidden_dim, self.hidden_dim)),
            nn.Tanh(),
            layer_init(nn.Linear(self.hidden_dim, self.action_dim), std=0.01),
            nn.Tanh(),
        )
        self.actor_logstd = nn.Parameter(
            torch.tensor([[-1.2, -1.2, -2.0, -0.7]], dtype=torch.float32)
        )

    def get_action_and_value(
        self, x: Tensor, action: Tensor | None = None, deterministic: bool = False
    ) -> tuple[Tensor, Tensor, Tensor, Tensor]:
        """Return normalized action, log-probability, entropy, and value."""
        action_mean = self.actor_mean(x)
        action_logstd = self.actor_logstd.expand_as(action_mean)
        action_std = torch.exp(action_logstd)
        probs = Normal(action_mean, action_std)
        if action is None:
            action = action_mean if deterministic else probs.sample()
        return action, probs.log_prob(action).sum(1), probs.entropy().sum(1), self.critic(x)


def save_tracker_checkpoint(
    path: Path,
    agent: TrackerPPOAgent,
    *,
    global_step: int = 0,
    extra_metadata: dict[str, Any] | None = None,
) -> None:
    """Save a tracker checkpoint with enough metadata for inference validation."""
    checkpoint = {
        "model_state_dict": agent.state_dict(),
        "observation_layout": REFERENCE_TRACKER_LAYOUT,
        "policy_arch": REFERENCE_TRACKER_POLICY_ARCH,
        "obs_dim": agent.obs_dim,
        "action_dim": agent.action_dim,
        "hidden_dim": agent.hidden_dim,
        "global_step": int(global_step),
    }
    if extra_metadata:
        checkpoint.update(extra_metadata)
    path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(checkpoint, path)


def load_tracker_checkpoint(
    path: Path,
    device: torch.device | str = "cpu",
) -> tuple[TrackerPPOAgent, dict[str, Any]]:
    """Load a v54 tracker checkpoint and validate its observation layout."""
    checkpoint = torch.load(path, map_location=device, weights_only=False)
    if not isinstance(checkpoint, dict) or "model_state_dict" not in checkpoint:
        raise ValueError(f"Unsupported v54 tracker checkpoint: {path}")
    if checkpoint.get("observation_layout") != REFERENCE_TRACKER_LAYOUT:
        raise ValueError(
            f"Checkpoint layout {checkpoint.get('observation_layout')!r} does not match "
            f"{REFERENCE_TRACKER_LAYOUT!r}."
        )
    obs_dim = int(checkpoint.get("obs_dim", REFERENCE_TRACKER_OBS_DIM))
    action_dim = int(checkpoint.get("action_dim", 4))
    hidden_dim = int(checkpoint.get("hidden_dim", 256))
    agent = TrackerPPOAgent(
        obs_dim=obs_dim,
        action_dim=action_dim,
        hidden_dim=hidden_dim,
    ).to(device)
    agent.load_state_dict(checkpoint["model_state_dict"], strict=True)
    agent.eval()
    return agent, checkpoint


def action_bounds_from_config(
    config: Any,
    rp_limit_deg: float = 50.0,
) -> tuple[np.ndarray, np.ndarray]:
    """Return attitude-control action bounds used by trainer and controller."""
    drone_params = load_params(config.sim.physics, config.sim.drone_model)
    thrust_min = float(drone_params["thrust_min"] * 4)
    thrust_max = float(drone_params["thrust_max"] * 4)
    rp_limit = float(np.deg2rad(rp_limit_deg))
    action_low = np.array([-rp_limit, -rp_limit, -np.pi / 2.0, thrust_min], dtype=np.float32)
    action_high = np.array([rp_limit, rp_limit, np.pi / 2.0, thrust_max], dtype=np.float32)
    return action_low, action_high


def scale_action(
    action_norm: np.ndarray,
    action_low: np.ndarray,
    action_high: np.ndarray,
) -> np.ndarray:
    """Scale normalized [-1, 1] actions into physical attitude commands."""
    action_norm = np.clip(np.asarray(action_norm, dtype=np.float32), -1.0, 1.0)
    return action_norm * ((action_high - action_low) / 2.0) + ((action_high + action_low) / 2.0)


def normalize_action(
    action: np.ndarray,
    action_low: np.ndarray,
    action_high: np.ndarray,
) -> np.ndarray:
    """Convert physical attitude commands back to normalized PPO actions."""
    action = np.asarray(action, dtype=np.float32)
    return np.clip(
        2.0 * (action - (action_low + action_high) / 2.0) / (action_high - action_low),
        -1.0,
        1.0,
    )


def quat_to_rotmat(quat: np.ndarray) -> np.ndarray:
    """Convert an xyzw quaternion into a body-to-world rotation matrix."""
    x, y, z, w = np.asarray(quat, dtype=np.float32)
    xx, yy, zz = x * x, y * y, z * z
    xy, xz, yz = x * y, x * z, y * z
    wx, wy, wz = w * x, w * y, w * z
    return np.array(
        [
            [1.0 - 2.0 * (yy + zz), 2.0 * (xy - wz), 2.0 * (xz + wy)],
            [2.0 * (xy + wz), 1.0 - 2.0 * (xx + zz), 2.0 * (yz - wx)],
            [2.0 * (xz - wy), 2.0 * (yz + wx), 1.0 - 2.0 * (xx + yy)],
        ],
        dtype=np.float32,
    )


def safe_normalize(vector: np.ndarray, fallback: np.ndarray | None = None) -> np.ndarray:
    """Normalize a vector while returning a stable fallback for near-zero norms."""
    vec = np.asarray(vector, dtype=np.float32)
    norm = float(np.linalg.norm(vec))
    if norm > 1e-6:
        return (vec / norm).astype(np.float32)
    if fallback is None:
        fallback = np.array([1.0, 0.0, 0.0], dtype=np.float32)
    fallback = np.asarray(fallback, dtype=np.float32)
    fallback_norm = max(float(np.linalg.norm(fallback)), 1e-6)
    return (fallback / fallback_norm).astype(np.float32)


def tracker_history_row(obs: dict[str, Any]) -> np.ndarray:
    """Return the compact local-state row used in the tracker history channels."""
    quat = np.asarray(obs["quat"], dtype=np.float32)
    rot_t = quat_to_rotmat(quat).T
    vel_body = rot_t @ np.asarray(obs["vel"], dtype=np.float32)
    return np.concatenate(
        [
            np.asarray(obs["pos"], dtype=np.float32)[2:3],
            vel_body.astype(np.float32),
            np.asarray(obs["ang_vel"], dtype=np.float32),
        ]
    ).astype(np.float32)


class ReferenceTrajectoryGenerator:
    """Generate local reference targets for tracker training and Level3 inference."""

    def __init__(self, task: str = "level3"):
        """Select the tracker task family used for reference generation."""
        if task not in {"hover", "point", "gate_aperture", "level3"}:
            raise ValueError(f"Unsupported reference task: {task!r}")
        self.task = task
        self._step = 0
        self._anchor: np.ndarray | None = None

    def reset(self, obs: dict[str, Any]) -> None:
        """Reset task anchors at episode start."""
        self._step = 0
        pos = np.asarray(obs["pos"], dtype=np.float32)
        if self.task == "hover":
            self._anchor = np.array(
                [pos[0], pos[1], max(0.65, pos[2] + 0.35)],
                dtype=np.float32,
            )
        elif self.task == "point":
            self._anchor = pos + np.array([0.35, 0.0, 0.35], dtype=np.float32)
            self._anchor[2] = np.clip(self._anchor[2], 0.55, 1.2)
        else:
            self._anchor = None

    def reference(self, obs: dict[str, Any]) -> ReferenceFrame:
        """Create the next local reference frame from a raw race observation."""
        self._step += 1
        if self.task == "hover":
            return self._hover_reference(obs)
        if self.task == "point":
            return self._point_reference(obs)
        return self._gate_reference(obs)

    def _hover_reference(self, obs: dict[str, Any]) -> ReferenceFrame:
        target = np.asarray(self._anchor, dtype=np.float32)
        return self._make_reference(obs, target, target, target, "hover", 0, 0.0)

    def _point_reference(self, obs: dict[str, Any]) -> ReferenceFrame:
        target = np.asarray(self._anchor, dtype=np.float32)
        pos = np.asarray(obs["pos"], dtype=np.float32)
        direction = safe_normalize(target - pos)
        next_point = target + direction * 0.10
        lookahead = target + direction * 0.20
        return self._make_reference(obs, target, next_point, lookahead, "cruise", 1, 0.45)

    def _gate_reference(self, obs: dict[str, Any]) -> ReferenceFrame:
        pos = np.asarray(obs["pos"], dtype=np.float32)
        target_gate_raw = int(np.asarray(obs.get("target_gate", 0)).item())
        n_gates = int(np.asarray(obs["gates_pos"]).shape[0])
        target_gate = int(np.clip(target_gate_raw, 0, n_gates - 1))
        gate_pos = np.asarray(obs["gates_pos"][target_gate], dtype=np.float32)
        gate_rot = quat_to_rotmat(np.asarray(obs["gates_quat"][target_gate], dtype=np.float32))
        gate_local = gate_rot.T @ (pos - gate_pos)
        aperture = self._aperture_yz(obs, target_gate, gate_rot)

        if self.task == "gate_aperture":
            phase, phase_id, local_point, speed = self._gate_aperture_phase(gate_local, aperture)
        else:
            phase, phase_id, local_point, speed = self._level3_phase(gate_local, aperture)

        current = gate_pos + gate_rot @ local_point
        next_point = gate_pos + gate_rot @ np.array(
            [local_point[0] + max(0.10, speed * 0.18), local_point[1], local_point[2]],
            dtype=np.float32,
        )
        lookahead = gate_pos + gate_rot @ np.array(
            [local_point[0] + max(0.24, speed * 0.40), local_point[1], local_point[2]],
            dtype=np.float32,
        )
        return self._make_reference(obs, current, next_point, lookahead, phase, phase_id, speed)

    @staticmethod
    def _gate_aperture_phase(
        gate_local: np.ndarray, aperture: np.ndarray
    ) -> tuple[str, int, np.ndarray, float]:
        if gate_local[0] < -0.65:
            return (
                "cruise",
                1,
                np.array([-0.55, aperture[0], aperture[1]], dtype=np.float32),
                0.65,
            )
        if gate_local[0] < -0.25:
            return (
                "align",
                3,
                np.array([-0.22, aperture[0], aperture[1]], dtype=np.float32),
                0.42,
            )
        if gate_local[0] < 0.28:
            return "cross", 4, np.array([0.35, aperture[0], aperture[1]], dtype=np.float32), 0.55
        return (
            "recover",
            5,
            np.array([0.65, aperture[0], aperture[1]], dtype=np.float32),
            0.65,
        )

    @staticmethod
    def _level3_phase(
        gate_local: np.ndarray,
        aperture: np.ndarray,
    ) -> tuple[str, int, np.ndarray, float]:
        if gate_local[0] < -1.00:
            return "cruise", 1, np.array([-0.80, aperture[0], aperture[1]], dtype=np.float32), 0.85
        if gate_local[0] < -0.70:
            return (
                "slowdown",
                2,
                np.array([-0.55, aperture[0], aperture[1]], dtype=np.float32),
                0.55,
            )
        if gate_local[0] < -0.25:
            return "align", 3, np.array([-0.22, aperture[0], aperture[1]], dtype=np.float32), 0.38
        if gate_local[0] < 0.32:
            return "cross", 4, np.array([0.36, aperture[0], aperture[1]], dtype=np.float32), 0.55
        return "recover", 5, np.array([0.72, aperture[0], aperture[1]], dtype=np.float32), 0.75

    def _make_reference(
        self,
        obs: dict[str, Any],
        current: np.ndarray,
        next_point: np.ndarray,
        lookahead: np.ndarray,
        phase: str,
        phase_id: int,
        desired_speed: float,
    ) -> ReferenceFrame:
        pos = np.asarray(obs["pos"], dtype=np.float32)
        to_current = np.asarray(current, dtype=np.float32) - pos
        heading = safe_normalize(to_current[:3])
        heading[2] = 0.0
        heading = safe_normalize(heading)
        desired_velocity = safe_normalize(to_current) * float(desired_speed)
        gate_local, aperture = self._gate_context(obs)
        obstacle_relative, obstacle_distance, obstacle_detected = (
            self._nearest_visible_obstacle(obs)
        )
        target_gate = int(
            np.clip(
                np.asarray(obs.get("target_gate", 0)).item(),
                0,
                len(obs["gates_pos"]) - 1,
            )
        )
        return ReferenceFrame(
            phase=phase,
            phase_id=phase_id,
            target_gate=target_gate,
            current_point=np.asarray(current, dtype=np.float32),
            next_point=np.asarray(next_point, dtype=np.float32),
            lookahead_point=np.asarray(lookahead, dtype=np.float32),
            desired_velocity=desired_velocity.astype(np.float32),
            desired_heading=heading.astype(np.float32),
            desired_speed=float(desired_speed),
            gate_local_position=gate_local.astype(np.float32),
            aperture_yz=aperture.astype(np.float32),
            obstacle_relative=obstacle_relative.astype(np.float32),
            obstacle_distance=float(obstacle_distance),
            obstacle_detected=float(obstacle_detected),
        )

    def _gate_context(self, obs: dict[str, Any]) -> tuple[np.ndarray, np.ndarray]:
        target_gate = int(
            np.clip(
                np.asarray(obs.get("target_gate", 0)).item(),
                0,
                len(obs["gates_pos"]) - 1,
            )
        )
        gate_rot = quat_to_rotmat(np.asarray(obs["gates_quat"][target_gate], dtype=np.float32))
        gate_pos = np.asarray(obs["gates_pos"][target_gate], dtype=np.float32)
        pos = np.asarray(obs["pos"], dtype=np.float32)
        return gate_rot.T @ (pos - gate_pos), self._aperture_yz(obs, target_gate, gate_rot)

    @staticmethod
    def _aperture_yz(obs: dict[str, Any], target_gate: int, gate_rot: np.ndarray) -> np.ndarray:
        gate_pos = np.asarray(obs["gates_pos"][target_gate], dtype=np.float32)
        obstacles = np.asarray(obs["obstacles_pos"], dtype=np.float32)
        detected = np.asarray(obs.get("obstacles_visited", np.ones(len(obstacles))), dtype=bool)
        candidates = np.array(
            [[0.0, 0.0], [0.12, 0.0], [-0.12, 0.0], [0.0, 0.12], [0.0, -0.12]],
            dtype=np.float32,
        )
        best = candidates[0]
        best_score = -np.inf
        for candidate in candidates:
            clearance = 2.0
            for idx, obstacle in enumerate(obstacles):
                if idx < len(detected) and not detected[idx]:
                    continue
                local = gate_rot.T @ (obstacle - gate_pos)
                if -0.65 <= local[0] <= 0.85:
                    clearance = min(clearance, float(np.linalg.norm(local[1:3] - candidate)))
            score = clearance - 0.15 * float(np.linalg.norm(candidate))
            if score > best_score:
                best_score = score
                best = candidate
        return np.clip(best, -0.16, 0.16).astype(np.float32)

    @staticmethod
    def _nearest_visible_obstacle(obs: dict[str, Any]) -> tuple[np.ndarray, float, float]:
        pos = np.asarray(obs["pos"], dtype=np.float32)
        rot_t = quat_to_rotmat(np.asarray(obs["quat"], dtype=np.float32)).T
        obstacles = np.asarray(obs["obstacles_pos"], dtype=np.float32)
        detected = np.asarray(obs.get("obstacles_visited", np.ones(len(obstacles))), dtype=bool)
        best_rel = np.zeros(3, dtype=np.float32)
        best_dist = float("inf")
        best_detected = 0.0
        for idx, obstacle in enumerate(obstacles):
            if idx < len(detected) and not detected[idx]:
                continue
            rel = obstacle - pos
            dist = float(np.linalg.norm(rel))
            if dist < best_dist:
                best_dist = dist
                best_rel = rot_t @ rel
                best_detected = 1.0
        if not np.isfinite(best_dist):
            best_dist = 0.0
        return best_rel.astype(np.float32), best_dist, best_detected


class ReferenceTrackerObservation:
    """Build the v54 native tracker observation."""

    obs_dim = REFERENCE_TRACKER_OBS_DIM

    def build(
        self,
        obs: dict[str, Any],
        reference: ReferenceFrame,
        memory: TrackerMemory,
    ) -> np.ndarray:
        """Flatten raw state, planner reference, action memory, and local history."""
        pos = np.asarray(obs["pos"], dtype=np.float32)
        quat = np.asarray(obs["quat"], dtype=np.float32)
        vel = np.asarray(obs["vel"], dtype=np.float32)
        ang_vel = np.asarray(obs["ang_vel"], dtype=np.float32)
        rot = quat_to_rotmat(quat)
        rot_t = rot.T
        vel_body = rot_t @ vel
        ref_points = np.concatenate(
            [
                rot_t @ (reference.current_point - pos),
                rot_t @ (reference.next_point - pos),
                rot_t @ (reference.lookahead_point - pos),
            ]
        )
        desired_velocity_body = rot_t @ reference.desired_velocity
        heading_body = rot_t @ reference.desired_heading
        heading_error = np.array([heading_body[1], heading_body[0]], dtype=np.float32)
        phase = np.zeros(len(REFERENCE_TRACKER_PHASES), dtype=np.float32)
        phase[int(np.clip(reference.phase_id, 0, len(phase) - 1))] = 1.0
        obstacle = np.concatenate(
            [
                reference.obstacle_relative,
                np.array(
                    [reference.obstacle_distance, reference.obstacle_detected],
                    dtype=np.float32,
                ),
            ]
        )
        history = np.concatenate(memory.history).astype(np.float32)
        flat = np.concatenate(
            [
                pos[2:3],
                vel_body,
                ang_vel,
                rot.reshape(-1),
                ref_points,
                desired_velocity_body,
                np.array([reference.desired_speed], dtype=np.float32),
                heading_error,
                reference.gate_local_position,
                reference.aperture_yz,
                phase,
                obstacle,
                memory.last_action_norm,
                history,
            ]
        ).astype(np.float32)
        if flat.shape != (self.obs_dim,):
            raise ValueError(
                f"reference tracker obs dim mismatch: {flat.shape} != {(self.obs_dim,)}"
            )
        if not np.isfinite(flat).all():
            raise ValueError("reference tracker observation contains non-finite values")
        return flat


class ReferenceTrackerReward:
    """Dense tracker reward for v54 local reference following."""

    def __init__(
        self,
        pos_error_coef: float = 3.0,
        vel_error_coef: float = 0.6,
        heading_coef: float = 0.35,
        gate_center_coef: float = 1.0,
        obstacle_margin: float = 0.28,
        obstacle_coef: float = 0.8,
        action_coef: float = 0.02,
        action_delta_coef: float = 0.04,
        progress_bonus: float = 0.3,
        crash_penalty: float = 20.0,
    ):
        """Set reward coefficients for dense local reference tracking."""
        self.pos_error_coef = pos_error_coef
        self.vel_error_coef = vel_error_coef
        self.heading_coef = heading_coef
        self.gate_center_coef = gate_center_coef
        self.obstacle_margin = obstacle_margin
        self.obstacle_coef = obstacle_coef
        self.action_coef = action_coef
        self.action_delta_coef = action_delta_coef
        self.progress_bonus = progress_bonus
        self.crash_penalty = crash_penalty

    def compute(
        self,
        prev_obs: dict[str, Any],
        obs: dict[str, Any],
        reference: ReferenceFrame,
        action_norm: np.ndarray,
        prev_action_norm: np.ndarray,
        *,
        terminated: bool,
        truncated: bool,
    ) -> tuple[float, dict[str, float]]:
        """Compute the shaped tracker reward and diagnostics for one transition."""
        pos = np.asarray(obs["pos"], dtype=np.float32)
        prev_pos = np.asarray(prev_obs["pos"], dtype=np.float32)
        vel = np.asarray(obs["vel"], dtype=np.float32)
        pos_error = float(np.linalg.norm(reference.current_point - pos))
        prev_error = float(np.linalg.norm(reference.current_point - prev_pos))
        vel_error = float(np.linalg.norm(reference.desired_velocity - vel))
        heading = safe_normalize(reference.desired_heading)
        current_heading = quat_to_rotmat(np.asarray(obs["quat"], dtype=np.float32))[:, 0]
        current_heading[2] = 0.0
        current_heading = safe_normalize(current_heading)
        heading_error = 1.0 - float(np.clip(np.dot(heading, current_heading), -1.0, 1.0))
        gate_yz_error = float(
            np.linalg.norm(reference.gate_local_position[1:3] - reference.aperture_yz)
        )
        obstacle_penalty = 0.0
        if reference.obstacle_detected > 0.5 and reference.obstacle_distance < self.obstacle_margin:
            obstacle_penalty = self.obstacle_margin - reference.obstacle_distance
        action_penalty = float(np.mean(np.square(action_norm)))
        delta_penalty = float(np.mean(np.square(action_norm - prev_action_norm)))
        reward = (
            -self.pos_error_coef * pos_error
            - self.vel_error_coef * vel_error
            - self.heading_coef * heading_error
            - self.gate_center_coef * gate_yz_error
            - self.obstacle_coef * obstacle_penalty
            - self.action_coef * action_penalty
            - self.action_delta_coef * delta_penalty
            + self.progress_bonus * (prev_error - pos_error)
        )
        if terminated and not truncated:
            reward -= self.crash_penalty
        diagnostics = {
            "tracker/pos_error": pos_error,
            "tracker/vel_error": vel_error,
            "tracker/heading_error": heading_error,
            "tracker/gate_yz_error": gate_yz_error,
            "tracker/obstacle_penalty": obstacle_penalty,
            "tracker/action_penalty": action_penalty,
            "tracker/action_delta_penalty": delta_penalty,
        }
        return float(reward), diagnostics


class ReferenceTrackerEnv(gym.Env):
    """Single-env wrapper that turns Level3 into a local reference-tracking task."""

    metadata = {"render_modes": []}

    def __init__(
        self,
        *,
        config_name: str = "level3.toml",
        task: str = "level3",
        max_episode_steps: int = 500,
        seed: int = -1,
        render: bool = False,
        rp_limit_deg: float = 50.0,
    ):
        """Wrap the Level3 race env as a single-env tracker training task."""
        super().__init__()
        self.config_name = config_name
        self.config = load_config(Path(__file__).parents[2] / "config" / config_name)
        self.config.sim.render = bool(render)
        if int(seed) >= 0:
            self.config.env.seed = int(seed)
        self.base_env = gym.make(
            self.config.env.id,
            freq=self.config.env.freq,
            sim_config=self.config.sim,
            sensor_range=self.config.env.sensor_range,
            control_mode=self.config.env.control_mode,
            track=self.config.env.track,
            disturbances=self.config.env.get("disturbances"),
            randomizations=self.config.env.get("randomizations"),
            seed=self.config.env.seed,
        )
        self.base_env = JaxToNumpy(self.base_env)
        self.generator = ReferenceTrajectoryGenerator(task)
        self.observation_builder = ReferenceTrackerObservation()
        self.reward_model = ReferenceTrackerReward()
        self.max_episode_steps = int(max_episode_steps)
        self.action_low, self.action_high = action_bounds_from_config(
            self.config,
            rp_limit_deg,
        )
        self.action_space = spaces.Box(low=-1.0, high=1.0, shape=(4,), dtype=np.float32)
        self.observation_space = spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(REFERENCE_TRACKER_OBS_DIM,),
            dtype=np.float32,
        )
        self._raw_obs: dict[str, Any] | None = None
        self._reference: ReferenceFrame | None = None
        self._memory: TrackerMemory | None = None
        self._steps = 0
        self.last_diagnostics: dict[str, float] = {}

    def reset(
        self,
        *,
        seed: int | None = None,
        options: dict[str, Any] | None = None,
    ) -> tuple[np.ndarray, dict[str, Any]]:
        """Reset the wrapped race env and rebuild tracker memory/reference."""
        raw_obs, info = self.base_env.reset(seed=seed, options=options)
        self.generator.reset(raw_obs)
        self._memory = TrackerMemory.from_observation(raw_obs)
        self._reference = self.generator.reference(raw_obs)
        self._raw_obs = raw_obs
        self._steps = 0
        self.last_diagnostics = {}
        return self.observation_builder.build(raw_obs, self._reference, self._memory), info

    def step(self, action: np.ndarray) -> tuple[np.ndarray, float, bool, bool, dict[str, Any]]:
        """Apply one normalized tracker action to the wrapped attitude-control env."""
        if self._raw_obs is None or self._reference is None or self._memory is None:
            raise RuntimeError("ReferenceTrackerEnv.step called before reset.")
        action_norm = np.clip(np.asarray(action, dtype=np.float32), -1.0, 1.0)
        sim_action = scale_action(action_norm, self.action_low, self.action_high)
        prev_obs = self._raw_obs
        prev_action = self._memory.last_action_norm.copy()
        raw_obs, _sparse_reward, terminated, truncated, info = self.base_env.step(sim_action)
        self._steps += 1
        truncated = bool(truncated or self._steps >= self.max_episode_steps)
        reward_obs = self._final_observation(raw_obs, info)
        reward, diagnostics = self.reward_model.compute(
            prev_obs,
            reward_obs,
            self._reference,
            action_norm,
            prev_action,
            terminated=bool(terminated),
            truncated=bool(truncated),
        )
        self._memory.update(reward_obs, action_norm)
        self._reference = self.generator.reference(reward_obs)
        self._raw_obs = reward_obs
        self.last_diagnostics = diagnostics | {
            "tracker/phase_id": float(self._reference.phase_id),
            "tracker/target_gate": float(self._reference.target_gate),
            "tracker/reward": float(reward),
        }
        observation = self.observation_builder.build(reward_obs, self._reference, self._memory)
        return observation, float(reward), bool(terminated), bool(truncated), info

    def close(self) -> None:
        """Close the wrapped environment."""
        self.base_env.close()

    @staticmethod
    def _final_observation(raw_obs: dict[str, Any], info: dict[str, Any]) -> dict[str, Any]:
        if isinstance(info, dict) and "final_observation" in info:
            final_obs = info["final_observation"]
            if isinstance(final_obs, dict):
                return final_obs
        if isinstance(info, dict) and "reset_observations" in info:
            reset_obs = info["reset_observations"]
            if isinstance(reset_obs, dict):
                return reset_obs
        return raw_obs
