"""Reference-trajectory tracker support for the Level3 v54 lane."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Self

import gymnasium as gym
import jax
import numpy as np
import torch
import torch.nn as nn
from drone_models.core import load_params
from gymnasium import spaces
from gymnasium.vector.utils import batch_space
from gymnasium.wrappers.jax_to_numpy import JaxToNumpy
from torch import Tensor
from torch.distributions.normal import Normal

from lsy_drone_racing.utils import load_config

REFERENCE_TRACKER_LAYOUT = "level3_reference_tracker_v1"
SEMANTIC_REFERENCE_TRACKER_LAYOUT = "level3_reference_tracker_semantic_v2"
COMMAND_REFERENCE_TRACKER_LAYOUT = "level3_reference_tracker_command_v3"
REFERENCE_TRACKER_POLICY_ARCH = "mlp_2x256_tanh"
REFERENCE_TRACKER_HISTORY = 2
REFERENCE_TRACKER_HISTORY_DIM = 7
REFERENCE_TRACKER_PHASES = (
    "hover",
    "cruise",
    "slowdown",
    "align",
    "cross",
    "recover",
)
REFERENCE_TRACKER_OBS_DIM = 65
REFERENCE_TRACKER_CLEAN_COMMAND_OBS_DIM = 56
REFERENCE_TRACKER_WAYPOINT_TYPES = (
    "pass_through",
    "hold_or_brake",
    "low_speed_through",
    "recover_speed",
)
REFERENCE_TRACKER_SEMANTIC_FEATURE_DIM = len(REFERENCE_TRACKER_WAYPOINT_TYPES) + 3
SEMANTIC_REFERENCE_TRACKER_OBS_DIM = (
    REFERENCE_TRACKER_OBS_DIM + REFERENCE_TRACKER_SEMANTIC_FEATURE_DIM
)
REFERENCE_TRACKER_OBSERVATION_LAYOUTS = (
    REFERENCE_TRACKER_LAYOUT,
    SEMANTIC_REFERENCE_TRACKER_LAYOUT,
    COMMAND_REFERENCE_TRACKER_LAYOUT,
)
REFERENCE_TRACKER_OBS_DIMS = {
    REFERENCE_TRACKER_LAYOUT: REFERENCE_TRACKER_OBS_DIM,
    SEMANTIC_REFERENCE_TRACKER_LAYOUT: SEMANTIC_REFERENCE_TRACKER_OBS_DIM,
    COMMAND_REFERENCE_TRACKER_LAYOUT: REFERENCE_TRACKER_CLEAN_COMMAND_OBS_DIM,
}
REFERENCE_COMMAND_TRACKER_TASKS = frozenset({"reference_command_no_gate_reward"})
SEMANTIC_REFERENCE_TRACKER_TASKS = REFERENCE_COMMAND_TRACKER_TASKS
FREE_SPACE_TRACKER_TASKS = frozenset(
    {
        "hover",
        "point_hold",
        "point_reach",
        "brake_to_point",
        "line_tracking",
        "heading_tracking",
        "multi_point_reference",
        "l_shape_tracking",
        "curve_tracking",
        "zigzag_or_lemniscate_tracking",
    }
) | SEMANTIC_REFERENCE_TRACKER_TASKS
GATE_TRACKER_TASKS = frozenset({"gate_aperture_reference", "level3"})
REFERENCE_TRACKER_TASK_ALIASES = {
    "point": "point_reach",
    "gate_aperture": "gate_aperture_reference",
    "semantic_reference": "reference_command_no_gate_reward",
    "semantic_planner_reference": "reference_command_no_gate_reward",
}
REFERENCE_TRACKER_TASKS = tuple(
    sorted(FREE_SPACE_TRACKER_TASKS | GATE_TRACKER_TASKS | set(REFERENCE_TRACKER_TASK_ALIASES))
)
TRACKER_ENV_MODES = ("auto", "free_space", "gate_aperture", "level3")
REFERENCE_TRACKER_REWARD_DEFAULTS = {
    "pos_error_coef": 3.0,
    "vel_error_coef": 0.6,
    "heading_coef": 0.35,
    "gate_center_coef": 1.0,
    "obstacle_margin": 0.28,
    "obstacle_coef": 0.8,
    "action_coef": 0.02,
    "action_delta_coef": 0.04,
    "progress_bonus": 0.3,
    "gate_x_progress_coef": 0.0,
    "gate_cross_bonus": 0.0,
    "gate_recover_bonus": 0.0,
    "gate_linger_penalty_coef": 0.0,
    "semantic_brake_speed_coef": 1.0,
    "semantic_slow_speed_coef": 0.8,
    "semantic_slow_stop_coef": 0.8,
    "semantic_recover_speed_coef": 0.4,
    "crash_penalty": 250.0,
}


@dataclass(frozen=True)
class ReferenceFrame:
    """Local trajectory target generated by the upper planner."""

    phase: str
    phase_id: int
    target_gate: int
    current_point: np.ndarray
    next_point: np.ndarray
    lookahead_point: np.ndarray
    desired_velocity: np.ndarray
    desired_heading: np.ndarray
    desired_speed: float
    gate_local_position: np.ndarray
    aperture_yz: np.ndarray
    obstacle_relative: np.ndarray
    obstacle_distance: float
    obstacle_detected: float
    waypoint_type: str = "pass_through"
    waypoint_type_id: int = 0
    stop_signal: float = 0.0
    brake_mask: float = 0.0
    slow_through_mask: float = 0.0


@dataclass(frozen=True)
class GeometricPlannerOutput:
    """Short-horizon local reference generated by the slow deterministic planner."""

    phase: str
    phase_id: int
    current_local: np.ndarray
    next_local: np.ndarray
    lookahead_local: np.ndarray
    desired_speed: float


@dataclass
class TrackerMemory:
    """Per-episode memory used by the observation builder."""

    history: list[np.ndarray]
    last_action_norm: np.ndarray

    @classmethod
    def from_observation(
        cls,
        obs: dict[str, Any],
        n_history: int = REFERENCE_TRACKER_HISTORY,
    ) -> Self:
        """Initialize tracker memory from the first raw environment observation."""
        basic = tracker_history_row(obs)
        return cls(
            history=[basic.copy() for _ in range(n_history)],
            last_action_norm=np.zeros(4, dtype=np.float32),
        )

    def update(self, obs: dict[str, Any], action_norm: np.ndarray) -> None:
        """Append one raw-observation history row and remember the latest action."""
        self.history.append(tracker_history_row(obs))
        self.history = self.history[-REFERENCE_TRACKER_HISTORY:]
        self.last_action_norm = np.clip(np.asarray(action_norm, dtype=np.float32), -1.0, 1.0)


def layer_init(layer: nn.Module, std: float = np.sqrt(2), bias_const: float = 0.0) -> nn.Module:
    """Orthogonally initialize a linear layer like the existing PPO agents."""
    torch.nn.init.orthogonal_(layer.weight, std)
    torch.nn.init.constant_(layer.bias, bias_const)
    return layer


class TrackerPPOAgent(nn.Module):
    """Small MLP PPO actor/critic for the reference-tracker observation."""

    def __init__(
        self,
        obs_dim: int = REFERENCE_TRACKER_OBS_DIM,
        action_dim: int = 4,
        hidden_dim: int = 256,
    ):
        """Build actor, critic, and learned action standard deviation."""
        super().__init__()
        self.obs_dim = int(obs_dim)
        self.action_dim = int(action_dim)
        self.hidden_dim = int(hidden_dim)
        self.critic = nn.Sequential(
            layer_init(nn.Linear(self.obs_dim, self.hidden_dim)),
            nn.Tanh(),
            layer_init(nn.Linear(self.hidden_dim, self.hidden_dim)),
            nn.Tanh(),
            layer_init(nn.Linear(self.hidden_dim, 1), std=1.0),
        )
        self.actor_mean = nn.Sequential(
            layer_init(nn.Linear(self.obs_dim, self.hidden_dim)),
            nn.Tanh(),
            layer_init(nn.Linear(self.hidden_dim, self.hidden_dim)),
            nn.Tanh(),
            layer_init(nn.Linear(self.hidden_dim, self.action_dim), std=0.01),
            nn.Tanh(),
        )
        self.actor_logstd = nn.Parameter(
            torch.tensor([[-1.2, -1.2, -2.0, -0.7]], dtype=torch.float32)
        )

    def get_action_and_value(
        self, x: Tensor, action: Tensor | None = None, deterministic: bool = False
    ) -> tuple[Tensor, Tensor, Tensor, Tensor]:
        """Return normalized action, log-probability, entropy, and value."""
        action_mean = self.actor_mean(x)
        action_logstd = self.actor_logstd.expand_as(action_mean)
        action_std = torch.exp(action_logstd)
        probs = Normal(action_mean, action_std)
        if action is None:
            action = action_mean if deterministic else probs.sample()
        return action, probs.log_prob(action).sum(1), probs.entropy().sum(1), self.critic(x)


def save_tracker_checkpoint(
    path: Path,
    agent: TrackerPPOAgent,
    *,
    global_step: int = 0,
    observation_layout: str = REFERENCE_TRACKER_LAYOUT,
    extra_metadata: dict[str, Any] | None = None,
) -> None:
    """Save a tracker checkpoint with enough metadata for inference validation."""
    expected_dim = tracker_obs_dim_for_layout(observation_layout)
    if int(agent.obs_dim) != expected_dim:
        raise ValueError(
            f"Agent obs_dim {agent.obs_dim} does not match {observation_layout!r} "
            f"dimension {expected_dim}."
        )
    checkpoint = {
        "model_state_dict": agent.state_dict(),
        "observation_layout": observation_layout,
        "policy_arch": REFERENCE_TRACKER_POLICY_ARCH,
        "obs_dim": agent.obs_dim,
        "action_dim": agent.action_dim,
        "hidden_dim": agent.hidden_dim,
        "global_step": int(global_step),
    }
    if extra_metadata:
        checkpoint.update(extra_metadata)
    checkpoint["observation_layout"] = observation_layout
    checkpoint["obs_dim"] = agent.obs_dim
    checkpoint["action_dim"] = agent.action_dim
    checkpoint["hidden_dim"] = agent.hidden_dim
    path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(checkpoint, path)


def load_tracker_checkpoint(
    path: Path,
    device: torch.device | str = "cpu",
    *,
    expected_layout: str | None = REFERENCE_TRACKER_LAYOUT,
) -> tuple[TrackerPPOAgent, dict[str, Any]]:
    """Load a tracker checkpoint and validate its observation layout."""
    checkpoint = torch.load(path, map_location=device, weights_only=False)
    if not isinstance(checkpoint, dict) or "model_state_dict" not in checkpoint:
        raise ValueError(f"Unsupported v54 tracker checkpoint: {path}")
    layout = str(checkpoint.get("observation_layout", REFERENCE_TRACKER_LAYOUT))
    if layout not in REFERENCE_TRACKER_OBSERVATION_LAYOUTS:
        raise ValueError(f"Unsupported tracker checkpoint layout {layout!r}: {path}")
    if expected_layout is not None and layout != expected_layout:
        raise ValueError(
            f"Checkpoint layout {layout!r} does not match expected layout "
            f"{expected_layout!r}."
        )
    expected_dim = tracker_obs_dim_for_layout(layout)
    obs_dim = int(checkpoint.get("obs_dim", expected_dim))
    if obs_dim != expected_dim:
        raise ValueError(
            f"Checkpoint obs_dim {obs_dim} does not match {layout!r} dimension "
            f"{expected_dim}."
        )
    action_dim = int(checkpoint.get("action_dim", 4))
    hidden_dim = int(checkpoint.get("hidden_dim", 256))
    agent = TrackerPPOAgent(
        obs_dim=obs_dim,
        action_dim=action_dim,
        hidden_dim=hidden_dim,
    ).to(device)
    agent.load_state_dict(checkpoint["model_state_dict"], strict=True)
    agent.eval()
    return agent, checkpoint


def action_bounds_from_config(
    config: Any,
    rp_limit_deg: float = 50.0,
) -> tuple[np.ndarray, np.ndarray]:
    """Return attitude-control action bounds used by trainer and controller."""
    drone_params = load_params(config.sim.physics, config.sim.drone_model)
    thrust_min = float(drone_params["thrust_min"] * 4)
    thrust_max = float(drone_params["thrust_max"] * 4)
    rp_limit = float(np.deg2rad(rp_limit_deg))
    action_low = np.array([-rp_limit, -rp_limit, -np.pi / 2.0, thrust_min], dtype=np.float32)
    action_high = np.array([rp_limit, rp_limit, np.pi / 2.0, thrust_max], dtype=np.float32)
    return action_low, action_high


def scale_action(
    action_norm: np.ndarray,
    action_low: np.ndarray,
    action_high: np.ndarray,
) -> np.ndarray:
    """Scale normalized [-1, 1] actions into physical attitude commands."""
    action_norm = np.clip(np.asarray(action_norm, dtype=np.float32), -1.0, 1.0)
    return action_norm * ((action_high - action_low) / 2.0) + ((action_high + action_low) / 2.0)


def normalize_action(
    action: np.ndarray,
    action_low: np.ndarray,
    action_high: np.ndarray,
) -> np.ndarray:
    """Convert physical attitude commands back to normalized PPO actions."""
    action = np.asarray(action, dtype=np.float32)
    return np.clip(
        2.0 * (action - (action_low + action_high) / 2.0) / (action_high - action_low),
        -1.0,
        1.0,
    )


def quat_to_rotmat(quat: np.ndarray) -> np.ndarray:
    """Convert an xyzw quaternion into a body-to-world rotation matrix."""
    x, y, z, w = np.asarray(quat, dtype=np.float32)
    xx, yy, zz = x * x, y * y, z * z
    xy, xz, yz = x * y, x * z, y * z
    wx, wy, wz = w * x, w * y, w * z
    return np.array(
        [
            [1.0 - 2.0 * (yy + zz), 2.0 * (xy - wz), 2.0 * (xz + wy)],
            [2.0 * (xy + wz), 1.0 - 2.0 * (xx + zz), 2.0 * (yz - wx)],
            [2.0 * (xz - wy), 2.0 * (yz + wx), 1.0 - 2.0 * (xx + yy)],
        ],
        dtype=np.float32,
    )


def gate_local_axis_velocity_x(obs: dict[str, Any]) -> float:
    """Return signed drone velocity along the current target gate's local X axis."""
    gates_pos = np.asarray(obs.get("gates_pos", []), dtype=np.float32)
    gates_quat = np.asarray(obs.get("gates_quat", []), dtype=np.float32)
    gate_count = min(len(gates_pos), len(gates_quat))
    if gate_count <= 0:
        return 0.0
    raw_target = int(np.asarray(obs.get("target_gate", 0)).item())
    target_gate = int(np.clip(raw_target, 0, gate_count - 1))
    vel = np.asarray(obs.get("vel", np.zeros(3)), dtype=np.float32)
    if vel.shape != (3,) or not np.isfinite(vel).all():
        return 0.0
    gate_rot = quat_to_rotmat(gates_quat[target_gate])
    return float((gate_rot.T @ vel)[0])


def safe_normalize(vector: np.ndarray, fallback: np.ndarray | None = None) -> np.ndarray:
    """Normalize a vector while returning a stable fallback for near-zero norms."""
    vec = np.asarray(vector, dtype=np.float32)
    norm = float(np.linalg.norm(vec))
    if norm > 1e-6:
        return (vec / norm).astype(np.float32)
    if fallback is None:
        fallback = np.array([1.0, 0.0, 0.0], dtype=np.float32)
    fallback = np.asarray(fallback, dtype=np.float32)
    fallback_norm = max(float(np.linalg.norm(fallback)), 1e-6)
    return (fallback / fallback_norm).astype(np.float32)


def tracker_obs_dim_for_layout(layout: str) -> int:
    """Return the tracker observation dimension for a named layout."""
    if layout not in REFERENCE_TRACKER_OBS_DIMS:
        raise ValueError(f"Unsupported reference tracker observation layout: {layout!r}")
    return int(REFERENCE_TRACKER_OBS_DIMS[layout])


def default_tracker_observation_layout(task: str, requested_layout: str = "auto") -> str:
    """Resolve the observation layout for a tracker task."""
    canonical = normalize_tracker_task(task)
    if requested_layout == "auto":
        return (
            COMMAND_REFERENCE_TRACKER_LAYOUT
            if canonical in SEMANTIC_REFERENCE_TRACKER_TASKS
            else REFERENCE_TRACKER_LAYOUT
        )
    if requested_layout not in REFERENCE_TRACKER_OBSERVATION_LAYOUTS:
        raise ValueError(f"Unsupported tracker observation layout: {requested_layout!r}")
    return requested_layout


def waypoint_type_id(waypoint_type: str) -> int:
    """Return the stable integer id for a semantic waypoint type."""
    waypoint_type = {
        "through": "pass_through",
        "brake_or_hold": "hold_or_brake",
        "slow_through": "low_speed_through",
        "recover": "recover_speed",
    }.get(waypoint_type, waypoint_type)
    try:
        return REFERENCE_TRACKER_WAYPOINT_TYPES.index(waypoint_type)
    except ValueError as exc:
        raise ValueError(f"Unsupported waypoint_type: {waypoint_type!r}") from exc


def waypoint_semantic_values(
    waypoint_type: str,
    *,
    stop_signal: float | None = None,
    brake_mask: float | None = None,
    slow_through_mask: float | None = None,
) -> tuple[int, float, float, float]:
    """Return waypoint id and explicit behavior masks for the semantic v2 layout."""
    waypoint_type = {
        "through": "pass_through",
        "brake_or_hold": "hold_or_brake",
        "slow_through": "low_speed_through",
        "recover": "recover_speed",
    }.get(waypoint_type, waypoint_type)
    type_id = waypoint_type_id(waypoint_type)
    default_stop = 1.0 if waypoint_type == "hold_or_brake" else 0.0
    default_brake = 1.0 if waypoint_type == "hold_or_brake" else 0.0
    default_slow = 1.0 if waypoint_type == "low_speed_through" else 0.0
    return (
        type_id,
        float(default_stop if stop_signal is None else stop_signal),
        float(default_brake if brake_mask is None else brake_mask),
        float(default_slow if slow_through_mask is None else slow_through_mask),
    )


def waypoint_semantic_features(reference: ReferenceFrame) -> np.ndarray:
    """Encode waypoint intent for the semantic v2 tracker observation."""
    one_hot = np.zeros(len(REFERENCE_TRACKER_WAYPOINT_TYPES), dtype=np.float32)
    one_hot[
        int(np.clip(reference.waypoint_type_id, 0, len(REFERENCE_TRACKER_WAYPOINT_TYPES) - 1))
    ] = 1.0
    masks = np.array(
        [
            reference.stop_signal,
            reference.brake_mask,
            reference.slow_through_mask,
        ],
        dtype=np.float32,
    )
    return np.concatenate([one_hot, masks]).astype(np.float32)


def normalize_tracker_task(task: str) -> str:
    """Return the canonical tracker task name while preserving legacy aliases."""
    canonical = REFERENCE_TRACKER_TASK_ALIASES.get(task, task)
    if canonical not in FREE_SPACE_TRACKER_TASKS | GATE_TRACKER_TASKS:
        raise ValueError(f"Unsupported reference task: {task!r}")
    return canonical


def tracker_env_mode_from_config(config: Any, task: str, requested_mode: str = "auto") -> str:
    """Resolve the tracker training environment mode from CLI and config."""
    requested = str(requested_mode)
    if requested not in TRACKER_ENV_MODES:
        raise ValueError(f"Unsupported tracker_env_mode: {requested!r}")
    if requested != "auto":
        mode = requested
    else:
        train_cfg = config.get("train", {}) if hasattr(config, "get") else {}
        tracker_cfg = train_cfg.get("reference_tracker", {}) if hasattr(train_cfg, "get") else {}
        mode = str(tracker_cfg.get("env_mode", "auto"))
        if mode == "auto":
            mode = _default_tracker_env_mode(task)
    if mode not in TRACKER_ENV_MODES[1:]:
        raise ValueError(f"Unsupported tracker_env_mode: {mode!r}")
    _validate_tracker_env_mode(task, mode)
    return mode


def _default_tracker_env_mode(task: str) -> str:
    if task in FREE_SPACE_TRACKER_TASKS:
        return "free_space"
    if task == "gate_aperture_reference":
        return "gate_aperture"
    return "level3"


def _validate_tracker_env_mode(task: str, mode: str) -> None:
    if mode == "free_space" and task not in FREE_SPACE_TRACKER_TASKS:
        raise ValueError(f"Task {task!r} is not valid for free_space tracker mode.")
    if mode == "gate_aperture" and task != "gate_aperture_reference":
        raise ValueError(f"Task {task!r} is not valid for gate_aperture tracker mode.")
    if mode == "level3" and task != "level3":
        raise ValueError(f"Task {task!r} is not valid for level3 tracker mode.")


def point_on_polyline(
    points: list[np.ndarray],
    distance_along: float,
) -> tuple[np.ndarray, np.ndarray]:
    """Return a target point and local direction at a distance along a polyline."""
    remaining = float(distance_along)
    for start, end in zip(points[:-1], points[1:], strict=True):
        segment = np.asarray(end, dtype=np.float32) - np.asarray(start, dtype=np.float32)
        length = float(np.linalg.norm(segment))
        if length <= 1e-6:
            continue
        direction = segment / length
        if remaining <= length:
            return (np.asarray(start, dtype=np.float32) + direction * remaining).astype(
                np.float32
            ), direction.astype(np.float32)
        remaining -= length
    last_direction = safe_normalize(points[-1] - points[-2])
    return np.asarray(points[-1], dtype=np.float32), last_direction.astype(np.float32)


def polyline_length(points: list[np.ndarray]) -> float:
    """Return total length of a polyline."""
    total = 0.0
    for start, end in zip(points[:-1], points[1:], strict=True):
        total += float(np.linalg.norm(np.asarray(end) - np.asarray(start)))
    return total


def lerp(start: np.ndarray, end: np.ndarray, alpha: float) -> np.ndarray:
    """Linearly interpolate between two 3D points."""
    t = float(np.clip(alpha, 0.0, 1.0))
    return (
        np.asarray(start, dtype=np.float32)
        + (np.asarray(end, dtype=np.float32) - np.asarray(start, dtype=np.float32)) * t
    ).astype(np.float32)


def tracker_history_row(obs: dict[str, Any]) -> np.ndarray:
    """Return the compact local-state row used in the tracker history channels."""
    quat = np.asarray(obs["quat"], dtype=np.float32)
    rot_t = quat_to_rotmat(quat).T
    vel_body = rot_t @ np.asarray(obs["vel"], dtype=np.float32)
    return np.concatenate(
        [
            np.asarray(obs["pos"], dtype=np.float32)[2:3],
            vel_body.astype(np.float32),
            np.asarray(obs["ang_vel"], dtype=np.float32),
        ]
    ).astype(np.float32)


def _tree_index(tree: Any, index: Any) -> Any:
    """Index a nested observation/info tree without flattening nested dicts."""
    if isinstance(tree, dict):
        return {key: _tree_index(value, index) for key, value in tree.items()}
    return tree[index]


def _to_numpy_tree(tree: Any) -> Any:
    """Convert a JAX/numpy pytree to numpy arrays while preserving dictionaries."""
    if isinstance(tree, dict):
        return {key: _to_numpy_tree(value) for key, value in tree.items()}
    return np.asarray(tree)


def _mean_diagnostics(rows: list[dict[str, float]]) -> dict[str, float]:
    """Average per-world tracker diagnostics for compact W&B logging."""
    if not rows:
        return {}
    keys = sorted({key for row in rows for key in row})
    return {
        key: float(np.mean([row[key] for row in rows if key in row]))
        for key in keys
    }


class ReferenceTrajectoryGenerator:
    """Generate local reference targets for tracker training and Level3 inference."""

    def __init__(self, task: str = "level3", dt: float = 1.0 / 50.0):
        """Select the tracker task family used for reference generation."""
        self.task = normalize_tracker_task(task)
        self.dt = float(dt)
        self._step = 0
        self._origin: np.ndarray | None = None
        self._anchor: np.ndarray | None = None
        self._level3_planner = GeometricSlowGatePlanner()

    def reset(self, obs: dict[str, Any]) -> None:
        """Reset task anchors at episode start."""
        self._step = 0
        pos = np.asarray(obs["pos"], dtype=np.float32)
        if self.task in FREE_SPACE_TRACKER_TASKS:
            self._origin = np.array([0.0, 0.0, 0.65], dtype=np.float32)
        else:
            self._origin = np.array(
                [pos[0], pos[1], np.clip(max(0.65, pos[2] + 0.45), 0.55, 1.25)],
                dtype=np.float32,
            )
        if self.task == "hover":
            self._anchor = self._origin.copy()
        elif self.task in {"point_hold", "point_reach", "brake_to_point"}:
            offset = np.array([0.55, 0.0, 0.05], dtype=np.float32)
            if self.task == "brake_to_point":
                offset = np.array([0.75, 0.0, 0.05], dtype=np.float32)
            self._anchor = self._origin + offset
            self._anchor[2] = np.clip(self._anchor[2], 0.55, 1.25)
        else:
            self._anchor = None
        if self.task == "level3":
            self._level3_planner.reset(obs)

    def reference(self, obs: dict[str, Any]) -> ReferenceFrame:
        """Create the next local reference frame from a raw race observation."""
        self._step += 1
        if self.task in FREE_SPACE_TRACKER_TASKS:
            return self._free_space_reference(obs)
        return self._gate_reference(obs)

    def _free_space_reference(self, obs: dict[str, Any]) -> ReferenceFrame:
        if self.task == "hover":
            return self._hover_reference(obs)
        if self.task in {"point_hold", "point_reach"}:
            return self._point_reference(obs, hold=self.task == "point_hold")
        if self.task == "brake_to_point":
            return self._brake_to_point_reference(obs)
        if self.task == "line_tracking":
            points = [self._origin, self._origin + np.array([0.9, 0.0, 0.0], dtype=np.float32)]
            return self._polyline_reference(obs, points, speed=0.38)
        if self.task == "heading_tracking":
            return self._heading_reference(obs)
        if self.task == "multi_point_reference":
            points = [
                self._origin,
                self._origin + np.array([0.35, 0.00, 0.05], dtype=np.float32),
                self._origin + np.array([0.35, 0.35, 0.05], dtype=np.float32),
                self._origin + np.array([0.05, 0.35, 0.00], dtype=np.float32),
            ]
            return self._polyline_reference(obs, points, speed=0.35)
        if self.task == "l_shape_tracking":
            points = [
                self._origin,
                self._origin + np.array([0.65, 0.0, 0.0], dtype=np.float32),
                self._origin + np.array([0.65, 0.45, 0.0], dtype=np.float32),
            ]
            return self._polyline_reference(obs, points, speed=0.36)
        if self.task == "curve_tracking":
            return self._curve_reference(obs, speed=0.34, sharp=False)
        if self.task == "zigzag_or_lemniscate_tracking":
            return self._curve_reference(obs, speed=0.36, sharp=True)
        if self.task == "reference_command_no_gate_reward":
            return self._reference_command_no_gate_reward(obs)
        raise ValueError(f"Unsupported free-space tracker task: {self.task!r}")

    def _hover_reference(self, obs: dict[str, Any]) -> ReferenceFrame:
        target = np.asarray(self._anchor, dtype=np.float32)
        pos = np.asarray(obs["pos"], dtype=np.float32)
        error = target - pos
        dist = float(np.linalg.norm(error))
        speed = 0.0 if dist < 0.10 else min(0.35, max(0.06, 0.9 * dist))
        phase = "hover" if speed == 0.0 else ("slowdown" if dist < 0.22 else "cruise")
        phase_id = 0 if phase == "hover" else (2 if phase == "slowdown" else 1)
        direction = safe_normalize(error)
        return self._make_reference(
            obs,
            target,
            target + direction * 0.06,
            target + direction * 0.12,
            phase,
            phase_id,
            speed,
            use_gate_context=False,
        )

    def _point_reference(self, obs: dict[str, Any], *, hold: bool) -> ReferenceFrame:
        target = np.asarray(self._anchor, dtype=np.float32)
        pos = np.asarray(obs["pos"], dtype=np.float32)
        error = target - pos
        dist = float(np.linalg.norm(error))
        speed = 0.0 if hold and dist < 0.14 else min(0.42, max(0.08, 0.8 * dist))
        phase = "hover" if speed == 0.0 else ("slowdown" if dist < 0.25 else "cruise")
        phase_id = 0 if phase == "hover" else (2 if phase == "slowdown" else 1)
        direction = safe_normalize(error)
        next_point = target + direction * 0.08
        lookahead = target + direction * 0.16
        return self._make_reference(
            obs,
            target,
            next_point,
            lookahead,
            phase,
            phase_id,
            speed,
            use_gate_context=False,
        )

    def _brake_to_point_reference(self, obs: dict[str, Any]) -> ReferenceFrame:
        target = np.asarray(self._anchor, dtype=np.float32)
        pos = np.asarray(obs["pos"], dtype=np.float32)
        error = target - pos
        dist = float(np.linalg.norm(error))
        speed = 0.0 if dist < 0.22 else min(0.50, max(0.10, 0.55 * dist))
        phase = "slowdown" if dist < 0.45 else "cruise"
        phase_id = 2 if dist < 0.45 else 1
        if speed == 0.0:
            phase, phase_id = "hover", 0
        direction = safe_normalize(error)
        return self._make_reference(
            obs,
            target,
            target + direction * 0.08,
            target + direction * 0.16,
            phase,
            phase_id,
            speed,
            use_gate_context=False,
        )

    def _heading_reference(self, obs: dict[str, Any]) -> ReferenceFrame:
        pos = np.asarray(obs["pos"], dtype=np.float32)
        target = np.asarray(self._origin, dtype=np.float32)
        target[:2] = pos[:2]
        heading_point = pos + np.array([0.35, 0.0, 0.0], dtype=np.float32)
        return self._make_reference(
            obs,
            target,
            heading_point,
            heading_point + np.array([0.15, 0.0, 0.0], dtype=np.float32),
            "hover",
            0,
            0.0,
            desired_heading=np.array([1.0, 0.0, 0.0], dtype=np.float32),
            use_gate_context=False,
        )

    def _polyline_reference(
        self,
        obs: dict[str, Any],
        points: list[np.ndarray | None],
        *,
        speed: float,
    ) -> ReferenceFrame:
        valid_points = [np.asarray(p, dtype=np.float32) for p in points if p is not None]
        if len(valid_points) < 2:
            raise ValueError("polyline tracker task requires at least two points")
        distance_along = max(0.0, (self._step - 1) * self.dt * float(speed))
        total_length = polyline_length(valid_points)
        if distance_along >= total_length:
            terminal = valid_points[-1]
            direction = safe_normalize(valid_points[-1] - valid_points[-2])
            return self._make_reference(
                obs,
                terminal,
                terminal,
                terminal,
                "terminal_hold",
                0,
                0.0,
                desired_heading=direction,
                use_gate_context=False,
            )
        target, direction = point_on_polyline(valid_points, distance_along)
        next_point, _ = point_on_polyline(valid_points, distance_along + 0.12)
        lookahead, _ = point_on_polyline(valid_points, distance_along + 0.28)
        phase = "align" if np.linalg.norm(target - valid_points[-1]) < 0.18 else "cruise"
        phase_id = 3 if phase == "align" else 1
        return self._make_reference(
            obs,
            target,
            next_point,
            lookahead,
            phase,
            phase_id,
            speed,
            desired_heading=direction,
            use_gate_context=False,
        )

    def _curve_reference(self, obs: dict[str, Any], *, speed: float, sharp: bool) -> ReferenceFrame:
        origin = np.asarray(self._origin, dtype=np.float32)
        t = max(0.0, (self._step - 1) * self.dt)
        if sharp:
            x = min(1.0, speed * t)
            y = 0.20 * np.sin(2.0 * np.pi * x / 0.55)
            target = origin + np.array([x, y, 0.0], dtype=np.float32)
            x2 = min(1.0, x + 0.12)
            y2 = 0.20 * np.sin(2.0 * np.pi * x2 / 0.55)
            next_point = origin + np.array([x2, y2, 0.0], dtype=np.float32)
            x3 = min(1.0, x + 0.28)
            y3 = 0.20 * np.sin(2.0 * np.pi * x3 / 0.55)
            lookahead = origin + np.array([x3, y3, 0.0], dtype=np.float32)
        else:
            radius = 0.55
            theta = min(np.pi / 2.0, speed * t / radius)
            target = origin + np.array(
                [radius * np.sin(theta), radius * (1.0 - np.cos(theta)), 0.0],
                dtype=np.float32,
            )
            theta2 = min(np.pi / 2.0, theta + 0.12 / radius)
            next_point = origin + np.array(
                [radius * np.sin(theta2), radius * (1.0 - np.cos(theta2)), 0.0],
                dtype=np.float32,
            )
            theta3 = min(np.pi / 2.0, theta + 0.28 / radius)
            lookahead = origin + np.array(
                [radius * np.sin(theta3), radius * (1.0 - np.cos(theta3)), 0.0],
                dtype=np.float32,
            )
        heading = safe_normalize(next_point - target)
        return self._make_reference(
            obs,
            target,
            next_point,
            lookahead,
            "cruise",
            1,
            speed,
            desired_heading=heading,
            use_gate_context=False,
        )

    def _reference_command_no_gate_reward(self, obs: dict[str, Any]) -> ReferenceFrame:
        """Free-space command sequence with no gate/aperture reward semantics."""
        origin = np.asarray(self._origin, dtype=np.float32)
        points = [
            origin,
            origin + np.array([0.32, 0.00, 0.02], dtype=np.float32),
            origin + np.array([0.58, 0.00, 0.02], dtype=np.float32),
            origin + np.array([0.86, 0.00, 0.02], dtype=np.float32),
            origin + np.array([1.16, 0.08, 0.02], dtype=np.float32),
        ]
        step = max(0, self._step - 1)
        if step < 30:
            alpha = step / 30.0
            current = lerp(points[0], points[1], alpha)
            next_point = lerp(points[0], points[1], min(1.0, alpha + 0.18))
            lookahead = lerp(points[0], points[1], min(1.0, alpha + 0.40))
            waypoint_type = "pass_through"
            phase, phase_id, speed = "cruise", 1, 0.62
        elif step < 70:
            current = points[2]
            next_point = points[2]
            lookahead = points[3]
            waypoint_type = "hold_or_brake"
            phase, phase_id, speed = "slowdown", 2, 0.05
        elif step < 115:
            alpha = (step - 70) / 45.0
            current = lerp(points[2], points[3], alpha)
            next_point = lerp(points[2], points[3], min(1.0, alpha + 0.20))
            lookahead = lerp(points[2], points[3], min(1.0, alpha + 0.45))
            waypoint_type = "low_speed_through"
            phase, phase_id, speed = "cross", 4, 0.30
        else:
            alpha = min(1.0, (step - 115) / 45.0)
            current = lerp(points[3], points[4], alpha)
            next_point = lerp(points[3], points[4], min(1.0, alpha + 0.22))
            lookahead = points[4]
            waypoint_type = "recover_speed"
            phase, phase_id, speed = "recover", 5, 0.48 if alpha < 1.0 else 0.20
        heading = safe_normalize(next_point - current)
        return self._make_reference(
            obs,
            current,
            next_point,
            lookahead,
            phase,
            phase_id,
            speed,
            desired_heading=heading,
            waypoint_type=waypoint_type,
            use_gate_context=False,
        )

    def _gate_reference(self, obs: dict[str, Any]) -> ReferenceFrame:
        pos = np.asarray(obs["pos"], dtype=np.float32)
        target_gate_raw = int(np.asarray(obs.get("target_gate", 0)).item())
        n_gates = int(np.asarray(obs["gates_pos"]).shape[0])
        target_gate = int(np.clip(target_gate_raw, 0, n_gates - 1))
        gate_pos = np.asarray(obs["gates_pos"][target_gate], dtype=np.float32)
        gate_rot = quat_to_rotmat(np.asarray(obs["gates_quat"][target_gate], dtype=np.float32))
        gate_local = gate_rot.T @ (pos - gate_pos)
        aperture = self._aperture_yz(obs, target_gate, gate_rot)

        if self.task == "gate_aperture_reference":
            phase, phase_id, local_point, speed = self._gate_aperture_phase(gate_local, aperture)
            current = gate_pos + gate_rot @ local_point
            next_point = gate_pos + gate_rot @ np.array(
                [local_point[0] + max(0.10, speed * 0.18), local_point[1], local_point[2]],
                dtype=np.float32,
            )
            lookahead = gate_pos + gate_rot @ np.array(
                [local_point[0] + max(0.24, speed * 0.40), local_point[1], local_point[2]],
                dtype=np.float32,
            )
        else:
            plan = self._level3_planner.plan(
                obs=obs,
                gate_local=gate_local,
                aperture=aperture,
                gate_pos=gate_pos,
                gate_rot=gate_rot,
            )
            phase = plan.phase
            phase_id = plan.phase_id
            speed = plan.desired_speed
            current = gate_pos + gate_rot @ plan.current_local
            next_point = gate_pos + gate_rot @ plan.next_local
            lookahead = gate_pos + gate_rot @ plan.lookahead_local

        return self._make_reference(obs, current, next_point, lookahead, phase, phase_id, speed)

    @staticmethod
    def _gate_aperture_phase(
        gate_local: np.ndarray, aperture: np.ndarray
    ) -> tuple[str, int, np.ndarray, float]:
        if gate_local[0] < -0.65:
            return (
                "cruise",
                1,
                np.array([-0.55, aperture[0], aperture[1]], dtype=np.float32),
                0.65,
            )
        if gate_local[0] < -0.25:
            return (
                "align",
                3,
                np.array([-0.22, aperture[0], aperture[1]], dtype=np.float32),
                0.42,
            )
        if gate_local[0] < 0.28:
            return "cross", 4, np.array([0.35, aperture[0], aperture[1]], dtype=np.float32), 0.55
        return (
            "recover",
            5,
            np.array([0.65, aperture[0], aperture[1]], dtype=np.float32),
            0.65,
        )

    @staticmethod
    def _level3_phase(
        gate_local: np.ndarray,
        aperture: np.ndarray,
    ) -> tuple[str, int, np.ndarray, float]:
        if gate_local[0] < -1.00:
            return "cruise", 1, np.array([-0.80, aperture[0], aperture[1]], dtype=np.float32), 0.85
        if gate_local[0] < -0.70:
            return (
                "slowdown",
                2,
                np.array([-0.55, aperture[0], aperture[1]], dtype=np.float32),
                0.55,
            )
        if gate_local[0] < -0.25:
            return "align", 3, np.array([-0.22, aperture[0], aperture[1]], dtype=np.float32), 0.38
        if gate_local[0] < 0.32:
            return "cross", 4, np.array([0.36, aperture[0], aperture[1]], dtype=np.float32), 0.55
        return "recover", 5, np.array([0.72, aperture[0], aperture[1]], dtype=np.float32), 0.75

    def _make_reference(
        self,
        obs: dict[str, Any],
        current: np.ndarray,
        next_point: np.ndarray,
        lookahead: np.ndarray,
        phase: str,
        phase_id: int,
        desired_speed: float,
        *,
        desired_heading: np.ndarray | None = None,
        waypoint_type: str = "pass_through",
        stop_signal: float | None = None,
        brake_mask: float | None = None,
        slow_through_mask: float | None = None,
        use_gate_context: bool = True,
    ) -> ReferenceFrame:
        pos = np.asarray(obs["pos"], dtype=np.float32)
        to_current = np.asarray(current, dtype=np.float32) - pos
        heading = safe_normalize(to_current[:3] if desired_heading is None else desired_heading)
        heading[2] = 0.0
        heading = safe_normalize(heading)
        desired_velocity = safe_normalize(to_current) * float(desired_speed)
        if use_gate_context:
            gate_local, aperture = self._gate_context(obs)
            obstacle_relative, obstacle_distance, obstacle_detected = (
                self._nearest_visible_obstacle(obs)
            )
            target_gate = int(
                np.clip(
                    np.asarray(obs.get("target_gate", 0)).item(),
                    0,
                    len(obs["gates_pos"]) - 1,
                )
            )
        else:
            gate_local = np.zeros(3, dtype=np.float32)
            aperture = np.zeros(2, dtype=np.float32)
            obstacle_relative = np.zeros(3, dtype=np.float32)
            obstacle_distance = 10.0
            obstacle_detected = 0.0
            target_gate = 0
        semantic_id, semantic_stop, semantic_brake, semantic_slow = waypoint_semantic_values(
            waypoint_type,
            stop_signal=stop_signal,
            brake_mask=brake_mask,
            slow_through_mask=slow_through_mask,
        )
        return ReferenceFrame(
            phase=phase,
            phase_id=phase_id,
            target_gate=target_gate,
            current_point=np.asarray(current, dtype=np.float32),
            next_point=np.asarray(next_point, dtype=np.float32),
            lookahead_point=np.asarray(lookahead, dtype=np.float32),
            desired_velocity=desired_velocity.astype(np.float32),
            desired_heading=heading.astype(np.float32),
            desired_speed=float(desired_speed),
            gate_local_position=gate_local.astype(np.float32),
            aperture_yz=aperture.astype(np.float32),
            obstacle_relative=obstacle_relative.astype(np.float32),
            obstacle_distance=float(obstacle_distance),
            obstacle_detected=float(obstacle_detected),
            waypoint_type=waypoint_type,
            waypoint_type_id=semantic_id,
            stop_signal=semantic_stop,
            brake_mask=semantic_brake,
            slow_through_mask=semantic_slow,
        )

    def _gate_context(self, obs: dict[str, Any]) -> tuple[np.ndarray, np.ndarray]:
        target_gate = int(
            np.clip(
                np.asarray(obs.get("target_gate", 0)).item(),
                0,
                len(obs["gates_pos"]) - 1,
            )
        )
        gate_rot = quat_to_rotmat(np.asarray(obs["gates_quat"][target_gate], dtype=np.float32))
        gate_pos = np.asarray(obs["gates_pos"][target_gate], dtype=np.float32)
        pos = np.asarray(obs["pos"], dtype=np.float32)
        return gate_rot.T @ (pos - gate_pos), self._aperture_yz(obs, target_gate, gate_rot)

    @staticmethod
    def _aperture_yz(obs: dict[str, Any], target_gate: int, gate_rot: np.ndarray) -> np.ndarray:
        gate_pos = np.asarray(obs["gates_pos"][target_gate], dtype=np.float32)
        obstacles = np.asarray(obs["obstacles_pos"], dtype=np.float32)
        detected = np.asarray(obs.get("obstacles_visited", np.ones(len(obstacles))), dtype=bool)
        candidates = np.array(
            [[0.0, 0.0], [0.12, 0.0], [-0.12, 0.0], [0.0, 0.12], [0.0, -0.12]],
            dtype=np.float32,
        )
        best = candidates[0]
        best_score = -np.inf
        for candidate in candidates:
            clearance = 2.0
            for idx, obstacle in enumerate(obstacles):
                if idx < len(detected) and not detected[idx]:
                    continue
                local = gate_rot.T @ (obstacle - gate_pos)
                if -0.65 <= local[0] <= 0.85:
                    clearance = min(clearance, float(np.linalg.norm(local[1:3] - candidate)))
            score = clearance - 0.15 * float(np.linalg.norm(candidate))
            if score > best_score:
                best_score = score
                best = candidate
        return np.clip(best, -0.16, 0.16).astype(np.float32)

    @staticmethod
    def _nearest_visible_obstacle(obs: dict[str, Any]) -> tuple[np.ndarray, float, float]:
        pos = np.asarray(obs["pos"], dtype=np.float32)
        rot_t = quat_to_rotmat(np.asarray(obs["quat"], dtype=np.float32)).T
        obstacles = np.asarray(obs["obstacles_pos"], dtype=np.float32)
        detected = np.asarray(obs.get("obstacles_visited", np.ones(len(obstacles))), dtype=bool)
        best_rel = np.zeros(3, dtype=np.float32)
        best_dist = float("inf")
        best_detected = 0.0
        for idx, obstacle in enumerate(obstacles):
            if idx < len(detected) and not detected[idx]:
                continue
            rel = obstacle - pos
            dist = float(np.linalg.norm(rel))
            if dist < best_dist:
                best_dist = dist
                best_rel = rot_t @ rel
                best_detected = 1.0
        if not np.isfinite(best_dist):
            best_dist = 0.0
        return best_rel.astype(np.float32), best_dist, best_detected


class GeometricSlowGatePlanner:
    """Conservative state-machine planner for Level3 tracker integration smoke."""

    CRUISE_PRE_GATE_X = -1.05
    SLOWDOWN_PRE_GATE_X = -0.62
    ALIGN_PRE_GATE_X = -0.30
    APERTURE_X = 0.06
    POST_GATE_X = 0.44
    RECOVERY_X = 0.82
    OBSTACLE_CLEARANCE_M = 0.34
    MAX_REFERENCE_YZ_M = 0.24
    ALIGN_TO_CROSS_YZ_M = 0.22
    ALIGN_TO_CROSS_MAX_GATE_X_SPEED_MPS = 0.85
    NEAR_PLANE_BACKOUT_X_M = 0.35
    NEAR_PLANE_BACKOUT_YZ_M = 0.30
    CROSS_SPEED_MPS = 0.32
    CROSS_ENTRY_MAX_REFERENCE_STEP_M = 0.28

    def __init__(self) -> None:
        """Initialize gate/phase memory for hysteretic rolling replanning."""
        self._target_gate = -1
        self._phase_id = 1
        self._last_current_local: np.ndarray | None = None

    def reset(self, obs: dict[str, Any]) -> None:
        """Reset planner phase when a new episode starts."""
        self._target_gate = self._target_gate_from_obs(obs)
        self._phase_id = 1
        self._last_current_local = None

    def plan(
        self,
        *,
        obs: dict[str, Any],
        gate_local: np.ndarray,
        aperture: np.ndarray,
        gate_pos: np.ndarray,
        gate_rot: np.ndarray,
    ) -> GeometricPlannerOutput:
        """Return a short conservative reference horizon in the current gate frame."""
        target_gate = self._target_gate_from_obs(obs)
        if target_gate != self._target_gate:
            self._target_gate = target_gate
            self._phase_id = self._initial_phase_id(gate_local)
            self._last_current_local = None
        self._phase_id = self._advance_phase(self._phase_id, gate_local, aperture, obs)
        points, speed = self._phase_points(self._phase_id, aperture)
        points = self._avoid_visible_obstacles(
            obs=obs,
            gate_local=gate_local,
            gate_pos=gate_pos,
            gate_rot=gate_rot,
            points=points,
        )
        if self._phase_id == 4 and self._last_current_local is not None:
            points = self._clamp_cross_entry_reference(points, self._last_current_local)
        self._last_current_local = points[0].astype(np.float32).copy()
        phase = REFERENCE_TRACKER_PHASES[int(np.clip(self._phase_id, 0, 5))]
        return GeometricPlannerOutput(
            phase=phase,
            phase_id=int(self._phase_id),
            current_local=points[0].astype(np.float32),
            next_local=points[1].astype(np.float32),
            lookahead_local=points[2].astype(np.float32),
            desired_speed=float(speed),
        )

    @staticmethod
    def _target_gate_from_obs(obs: dict[str, Any]) -> int:
        gate_count = len(obs.get("gates_pos", []))
        if gate_count <= 0:
            return 0
        raw = int(np.asarray(obs.get("target_gate", 0)).item())
        return int(np.clip(raw, 0, gate_count - 1))

    @classmethod
    def _initial_phase_id(cls, gate_local: np.ndarray) -> int:
        x = float(gate_local[0])
        if x > -0.24:
            return 4
        if x > -0.72:
            return 3
        if x > -1.18:
            return 2
        return 1

    @classmethod
    def _advance_phase(
        cls,
        phase_id: int,
        gate_local: np.ndarray,
        aperture: np.ndarray,
        obs: dict[str, Any],
    ) -> int:
        x = float(gate_local[0])
        yz_error = float(np.linalg.norm(gate_local[1:3] - aperture))
        gate_speed = cls._gate_axis_speed(obs)
        phase = int(phase_id)
        if (
            phase >= 4
            and abs(x) < cls.NEAR_PLANE_BACKOUT_X_M
            and yz_error > cls.NEAR_PLANE_BACKOUT_YZ_M
        ):
            phase = 3
        if phase <= 1 and x > -1.18:
            phase = 2
        if phase <= 2 and x > -0.72:
            phase = 3
        aligned_enough = yz_error <= cls.ALIGN_TO_CROSS_YZ_M
        slow_enough = gate_speed <= cls.ALIGN_TO_CROSS_MAX_GATE_X_SPEED_MPS
        if phase <= 3 and x > -0.34 and aligned_enough and slow_enough:
            phase = 4
        return int(np.clip(phase, 1, 4))

    @staticmethod
    def _gate_axis_speed(obs: dict[str, Any]) -> float:
        return abs(gate_local_axis_velocity_x(obs))

    @classmethod
    def _phase_points(
        cls,
        phase_id: int,
        aperture: np.ndarray,
    ) -> tuple[list[np.ndarray], float]:
        yz = np.asarray(aperture, dtype=np.float32)
        pre_far = cls._local_point(cls.CRUISE_PRE_GATE_X, yz)
        pre_slow = cls._local_point(cls.SLOWDOWN_PRE_GATE_X, yz)
        pre_align = cls._local_point(cls.ALIGN_PRE_GATE_X, yz)
        aperture_point = cls._local_point(cls.APERTURE_X, yz)
        post_gate = cls._local_point(cls.POST_GATE_X, yz)
        recovery = cls._local_point(cls.RECOVERY_X, yz)
        recovery_far = cls._local_point(cls.RECOVERY_X + 0.28, yz)
        if phase_id <= 1:
            return [pre_far, pre_slow, pre_align], 0.82
        if phase_id == 2:
            return [pre_slow, pre_align, aperture_point], 0.48
        if phase_id == 3:
            return [pre_align, aperture_point, post_gate], 0.28
        if phase_id == 4:
            return [post_gate, recovery, recovery_far], cls.CROSS_SPEED_MPS
        return [recovery, recovery_far, cls._local_point(cls.RECOVERY_X + 0.52, yz)], 0.62

    @classmethod
    def _clamp_cross_entry_reference(
        cls,
        points: list[np.ndarray],
        previous_current: np.ndarray,
    ) -> list[np.ndarray]:
        previous = np.asarray(previous_current, dtype=np.float32)
        target = np.asarray(points[0], dtype=np.float32)
        delta = target - previous
        distance = float(np.linalg.norm(delta))
        if distance <= cls.CROSS_ENTRY_MAX_REFERENCE_STEP_M:
            return points
        clamped_current = previous + delta * (cls.CROSS_ENTRY_MAX_REFERENCE_STEP_M / distance)
        horizon_shift = clamped_current - target
        return [
            (np.asarray(point, dtype=np.float32) + horizon_shift).astype(np.float32)
            for point in points
        ]

    @staticmethod
    def _local_point(x: float, yz: np.ndarray) -> np.ndarray:
        return np.array([x, yz[0], yz[1]], dtype=np.float32)

    @classmethod
    def _avoid_visible_obstacles(
        cls,
        *,
        obs: dict[str, Any],
        gate_local: np.ndarray,
        gate_pos: np.ndarray,
        gate_rot: np.ndarray,
        points: list[np.ndarray],
    ) -> list[np.ndarray]:
        obstacles = np.asarray(obs.get("obstacles_pos", []), dtype=np.float32)
        detected = np.asarray(obs.get("obstacles_visited", np.ones(len(obstacles))), dtype=bool)
        if len(obstacles) == 0:
            return points
        adjusted = [point.copy() for point in points]
        for obs_idx, obstacle in enumerate(obstacles):
            if obs_idx < len(detected) and not bool(detected[obs_idx]):
                continue
            obstacle_local = gate_rot.T @ (obstacle - gate_pos)
            for point in adjusted:
                if not cls._obstacle_relevant_to_segment(gate_local, point, obstacle_local):
                    continue
                delta_yz = point[1:3] - obstacle_local[1:3]
                dist_yz = float(np.linalg.norm(delta_yz))
                if dist_yz >= cls.OBSTACLE_CLEARANCE_M:
                    continue
                if dist_yz < 1e-4:
                    delta_yz = np.array([1.0, 0.0], dtype=np.float32)
                    dist_yz = 1.0
                push = (cls.OBSTACLE_CLEARANCE_M - dist_yz) + 0.04
                point[1:3] += (delta_yz / dist_yz) * push
                point[1:3] = np.clip(
                    point[1:3],
                    -cls.MAX_REFERENCE_YZ_M,
                    cls.MAX_REFERENCE_YZ_M,
                )
        return adjusted

    @staticmethod
    def _obstacle_relevant_to_segment(
        gate_local: np.ndarray,
        point: np.ndarray,
        obstacle_local: np.ndarray,
    ) -> bool:
        lower_x = min(float(gate_local[0]), float(point[0])) - 0.20
        upper_x = max(float(gate_local[0]), float(point[0])) + 0.35
        return lower_x <= float(obstacle_local[0]) <= upper_x


class ReferenceTrackerObservation:
    """Build the v54 native tracker observation."""

    obs_dim = REFERENCE_TRACKER_OBS_DIM

    def __init__(self, layout: str = REFERENCE_TRACKER_LAYOUT):
        """Select the tracker observation layout."""
        if layout not in REFERENCE_TRACKER_OBSERVATION_LAYOUTS:
            raise ValueError(f"Unsupported tracker observation layout: {layout!r}")
        self.layout = layout
        self.obs_dim = tracker_obs_dim_for_layout(layout)

    def build(
        self,
        obs: dict[str, Any],
        reference: ReferenceFrame,
        memory: TrackerMemory,
    ) -> np.ndarray:
        """Flatten raw state, planner reference, action memory, and local history."""
        pos = np.asarray(obs["pos"], dtype=np.float32)
        quat = np.asarray(obs["quat"], dtype=np.float32)
        vel = np.asarray(obs["vel"], dtype=np.float32)
        ang_vel = np.asarray(obs["ang_vel"], dtype=np.float32)
        rot = quat_to_rotmat(quat)
        rot_t = rot.T
        vel_body = rot_t @ vel
        ref_points = np.concatenate(
            [
                rot_t @ (reference.current_point - pos),
                rot_t @ (reference.next_point - pos),
                rot_t @ (reference.lookahead_point - pos),
            ]
        )
        desired_velocity_body = rot_t @ reference.desired_velocity
        heading_body = rot_t @ reference.desired_heading
        heading_error = np.array([heading_body[1], heading_body[0]], dtype=np.float32)
        phase = np.zeros(len(REFERENCE_TRACKER_PHASES), dtype=np.float32)
        phase[int(np.clip(reference.phase_id, 0, len(phase) - 1))] = 1.0
        obstacle = np.concatenate(
            [
                reference.obstacle_relative,
                np.array(
                    [reference.obstacle_distance, reference.obstacle_detected],
                    dtype=np.float32,
                ),
            ]
        )
        history = np.concatenate(memory.history).astype(np.float32)
        clean_command_fields = [
            pos[2:3],
            vel_body,
            ang_vel,
            rot.reshape(-1),
            ref_points,
            desired_velocity_body,
            np.array([reference.desired_speed], dtype=np.float32),
            heading_error,
            memory.last_action_norm,
            history,
        ]
        if self.layout == COMMAND_REFERENCE_TRACKER_LAYOUT:
            flat = np.concatenate(
                [*clean_command_fields, waypoint_semantic_features(reference)]
            ).astype(np.float32)
        else:
            flat = np.concatenate(
                [
                    *clean_command_fields[:8],
                    reference.gate_local_position,
                    reference.aperture_yz,
                    phase,
                    obstacle,
                    *clean_command_fields[8:],
                ]
            ).astype(np.float32)
        if self.layout == SEMANTIC_REFERENCE_TRACKER_LAYOUT:
            flat = np.concatenate([flat, waypoint_semantic_features(reference)]).astype(
                np.float32
            )
        if flat.shape != (self.obs_dim,):
            raise ValueError(
                f"reference tracker obs dim mismatch: {flat.shape} != {(self.obs_dim,)}"
            )
        if not np.isfinite(flat).all():
            raise ValueError("reference tracker observation contains non-finite values")
        return flat


class ReferenceTrackerReward:
    """Legacy dense tracker reward for v54/v55 and gate-aperture diagnostics."""

    def __init__(
        self,
        pos_error_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS["pos_error_coef"],
        vel_error_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS["vel_error_coef"],
        heading_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS["heading_coef"],
        gate_center_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS["gate_center_coef"],
        obstacle_margin: float = REFERENCE_TRACKER_REWARD_DEFAULTS["obstacle_margin"],
        obstacle_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS["obstacle_coef"],
        action_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS["action_coef"],
        action_delta_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS["action_delta_coef"],
        progress_bonus: float = REFERENCE_TRACKER_REWARD_DEFAULTS["progress_bonus"],
        gate_x_progress_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS[
            "gate_x_progress_coef"
        ],
        gate_cross_bonus: float = REFERENCE_TRACKER_REWARD_DEFAULTS["gate_cross_bonus"],
        gate_recover_bonus: float = REFERENCE_TRACKER_REWARD_DEFAULTS[
            "gate_recover_bonus"
        ],
        gate_linger_penalty_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS[
            "gate_linger_penalty_coef"
        ],
        semantic_brake_speed_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS[
            "semantic_brake_speed_coef"
        ],
        semantic_slow_speed_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS[
            "semantic_slow_speed_coef"
        ],
        semantic_slow_stop_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS[
            "semantic_slow_stop_coef"
        ],
        semantic_recover_speed_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS[
            "semantic_recover_speed_coef"
        ],
        crash_penalty: float = REFERENCE_TRACKER_REWARD_DEFAULTS["crash_penalty"],
    ):
        """Set reward coefficients for dense local reference tracking."""
        self.pos_error_coef = float(pos_error_coef)
        self.vel_error_coef = float(vel_error_coef)
        self.heading_coef = float(heading_coef)
        self.gate_center_coef = float(gate_center_coef)
        self.obstacle_margin = float(obstacle_margin)
        self.obstacle_coef = float(obstacle_coef)
        self.action_coef = float(action_coef)
        self.action_delta_coef = float(action_delta_coef)
        self.progress_bonus = float(progress_bonus)
        self.gate_x_progress_coef = float(gate_x_progress_coef)
        self.gate_cross_bonus = float(gate_cross_bonus)
        self.gate_recover_bonus = float(gate_recover_bonus)
        self.gate_linger_penalty_coef = float(gate_linger_penalty_coef)
        self.semantic_brake_speed_coef = float(semantic_brake_speed_coef)
        self.semantic_slow_speed_coef = float(semantic_slow_speed_coef)
        self.semantic_slow_stop_coef = float(semantic_slow_stop_coef)
        self.semantic_recover_speed_coef = float(semantic_recover_speed_coef)
        self.crash_penalty = float(crash_penalty)

    def coefficients(self) -> dict[str, float]:
        """Return reward coefficients for checkpoint metadata and diagnostics."""
        return {
            name: float(getattr(self, name))
            for name in REFERENCE_TRACKER_REWARD_DEFAULTS
        }

    def compute(
        self,
        prev_obs: dict[str, Any],
        obs: dict[str, Any],
        reference: ReferenceFrame,
        action_norm: np.ndarray,
        prev_action_norm: np.ndarray,
        *,
        terminated: bool,
        truncated: bool,
    ) -> tuple[float, dict[str, float]]:
        """Compute the shaped tracker reward and diagnostics for one transition."""
        pos = np.asarray(obs["pos"], dtype=np.float32)
        prev_pos = np.asarray(prev_obs["pos"], dtype=np.float32)
        vel = np.asarray(obs["vel"], dtype=np.float32)
        pos_error = float(np.linalg.norm(reference.current_point - pos))
        prev_error = float(np.linalg.norm(reference.current_point - prev_pos))
        vel_error = float(np.linalg.norm(reference.desired_velocity - vel))
        heading = safe_normalize(reference.desired_heading)
        current_heading = quat_to_rotmat(np.asarray(obs["quat"], dtype=np.float32))[:, 0]
        current_heading[2] = 0.0
        current_heading = safe_normalize(current_heading)
        heading_error = 1.0 - float(np.clip(np.dot(heading, current_heading), -1.0, 1.0))
        gate_yz_error = float(
            np.linalg.norm(reference.gate_local_position[1:3] - reference.aperture_yz)
        )
        obstacle_penalty = 0.0
        if reference.obstacle_detected > 0.5 and reference.obstacle_distance < self.obstacle_margin:
            obstacle_penalty = self.obstacle_margin - reference.obstacle_distance
        action_penalty = float(np.mean(np.square(action_norm)))
        delta_penalty = float(np.mean(np.square(action_norm - prev_action_norm)))
        gate_terms = self._gate_completion_terms(prev_obs, obs, reference, vel)
        semantic_terms = self._semantic_terms(reference, vel)
        reward = (
            -self.pos_error_coef * pos_error
            - self.vel_error_coef * vel_error
            - self.heading_coef * heading_error
            - self.gate_center_coef * gate_yz_error
            - self.obstacle_coef * obstacle_penalty
            - self.action_coef * action_penalty
            - self.action_delta_coef * delta_penalty
            + self.progress_bonus * (prev_error - pos_error)
            + self.gate_x_progress_coef * gate_terms["gate_x_progress_aligned_m"]
            + self.gate_cross_bonus * gate_terms["valid_aperture_cross_event"]
            + self.gate_recover_bonus * gate_terms["post_gate_recovery_event"]
            - self.gate_linger_penalty_coef * gate_terms["near_plane_linger_event"]
            - self.semantic_brake_speed_coef * semantic_terms["brake_hold_speed_excess"]
            - self.semantic_slow_speed_coef * semantic_terms["slow_through_speed_error"]
            - self.semantic_slow_stop_coef * semantic_terms["slow_through_stop_error"]
            - self.semantic_recover_speed_coef * semantic_terms["recover_speed_error"]
        )
        if terminated and not truncated:
            reward -= self.crash_penalty
        diagnostics = {
            "tracker/pos_error": pos_error,
            "tracker/vel_error": vel_error,
            "tracker/heading_error": heading_error,
            "tracker/gate_yz_error": gate_yz_error,
            "tracker/obstacle_penalty": obstacle_penalty,
            "tracker/action_penalty": action_penalty,
            "tracker/action_delta_penalty": delta_penalty,
            "tracker/gate_x": gate_terms["gate_x"],
            "tracker/gate_x_progress": gate_terms["gate_x_progress_m"],
            "tracker/gate_x_progress_aligned": gate_terms["gate_x_progress_aligned_m"],
            "tracker/gate_current_yz_error": gate_terms["current_aperture_yz_error"],
            "tracker/valid_aperture_cross_event": gate_terms["valid_aperture_cross_event"],
            "tracker/post_gate_recovery_event": gate_terms["post_gate_recovery_event"],
            "tracker/near_plane_linger_event": gate_terms["near_plane_linger_event"],
            "tracker/waypoint_type_id": float(reference.waypoint_type_id),
            "tracker/stop_signal": float(reference.stop_signal),
            "tracker/brake_mask": float(reference.brake_mask),
            "tracker/slow_through_mask": float(reference.slow_through_mask),
            "tracker/desired_speed_error": semantic_terms["desired_speed_error"],
            "tracker/brake_hold_speed_excess": semantic_terms["brake_hold_speed_excess"],
            "tracker/slow_through_speed_error": semantic_terms["slow_through_speed_error"],
            "tracker/slow_through_stop_error": semantic_terms["slow_through_stop_error"],
            "tracker/recover_speed_error": semantic_terms["recover_speed_error"],
        }
        return float(reward), diagnostics

    @staticmethod
    def _semantic_terms(reference: ReferenceFrame, vel: np.ndarray) -> dict[str, float]:
        """Return generic command behavior diagnostics and optional reward terms."""
        speed = float(np.linalg.norm(vel))
        desired_speed_error = abs(speed - float(reference.desired_speed))
        brake_excess = max(0.0, speed - 0.12) * float(reference.brake_mask)
        slow_speed_error = desired_speed_error * float(reference.slow_through_mask)
        slow_stop_error = max(0.0, 0.12 - speed) * float(reference.slow_through_mask)
        recover_mask = 1.0 if reference.waypoint_type == "recover_speed" else 0.0
        recover_speed_error = desired_speed_error * recover_mask
        return {
            "desired_speed_error": desired_speed_error,
            "brake_hold_speed_excess": brake_excess,
            "slow_through_speed_error": slow_speed_error,
            "slow_through_stop_error": slow_stop_error,
            "recover_speed_error": recover_speed_error,
        }

    @staticmethod
    def _gate_completion_terms(
        prev_obs: dict[str, Any],
        obs: dict[str, Any],
        reference: ReferenceFrame,
        vel: np.ndarray,
    ) -> dict[str, float]:
        """Return gate-crossing shaping terms for gate-aperture training."""
        terms = {
            "gate_x": 0.0,
            "gate_x_progress_m": 0.0,
            "gate_x_progress_aligned_m": 0.0,
            "current_aperture_yz_error": 0.0,
            "valid_aperture_cross_event": 0.0,
            "post_gate_recovery_event": 0.0,
            "near_plane_linger_event": 0.0,
        }
        try:
            prev_gate_local = ReferenceTrackerReward._target_gate_local(
                prev_obs,
                reference.target_gate,
            )
            gate_local = ReferenceTrackerReward._target_gate_local(
                obs,
                reference.target_gate,
            )
        except (KeyError, IndexError, ValueError):
            return terms

        prev_x = float(prev_gate_local[0])
        gate_x = float(gate_local[0])
        gate_x_progress = max(0.0, gate_x - prev_x)
        yz_error = float(np.linalg.norm(gate_local[1:3] - reference.aperture_yz))
        alignment_scale = max(0.0, 1.0 - yz_error / 0.32)
        speed = float(np.linalg.norm(vel))

        terms["gate_x"] = gate_x
        terms["gate_x_progress_m"] = gate_x_progress
        terms["gate_x_progress_aligned_m"] = gate_x_progress * alignment_scale
        terms["current_aperture_yz_error"] = yz_error
        if prev_x < 0.0 <= gate_x and yz_error <= 0.32:
            terms["valid_aperture_cross_event"] = 1.0
        if gate_x >= 0.35 and speed <= 0.65:
            terms["post_gate_recovery_event"] = 1.0
        if -0.32 <= gate_x < -0.20 and yz_error <= 0.12 and speed <= 0.12:
            terms["near_plane_linger_event"] = 1.0
        return terms

    @staticmethod
    def _target_gate_local(obs: dict[str, Any], target_gate: int) -> np.ndarray:
        gates_pos = np.asarray(obs["gates_pos"], dtype=np.float32)
        gates_quat = np.asarray(obs["gates_quat"], dtype=np.float32)
        target_gate = int(np.clip(target_gate, 0, len(gates_pos) - 1))
        gate_pos = gates_pos[target_gate]
        gate_rot = quat_to_rotmat(gates_quat[target_gate])
        pos = np.asarray(obs["pos"], dtype=np.float32)
        return (gate_rot.T @ (pos - gate_pos)).astype(np.float32)


LegacyTrackerReward = ReferenceTrackerReward


class ReferenceCommandReward:
    """Clean v60 command-tracker reward with no gate, obstacle, or race terms."""

    COEFFICIENT_NAMES = (
        "pos_error_coef",
        "vel_error_coef",
        "heading_coef",
        "action_coef",
        "action_delta_coef",
        "progress_bonus",
        "semantic_brake_speed_coef",
        "semantic_slow_speed_coef",
        "semantic_slow_stop_coef",
        "semantic_recover_speed_coef",
        "crash_penalty",
    )

    def __init__(
        self,
        pos_error_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS["pos_error_coef"],
        vel_error_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS["vel_error_coef"],
        heading_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS["heading_coef"],
        action_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS["action_coef"],
        action_delta_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS["action_delta_coef"],
        progress_bonus: float = REFERENCE_TRACKER_REWARD_DEFAULTS["progress_bonus"],
        semantic_brake_speed_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS[
            "semantic_brake_speed_coef"
        ],
        semantic_slow_speed_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS[
            "semantic_slow_speed_coef"
        ],
        semantic_slow_stop_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS[
            "semantic_slow_stop_coef"
        ],
        semantic_recover_speed_coef: float = REFERENCE_TRACKER_REWARD_DEFAULTS[
            "semantic_recover_speed_coef"
        ],
        crash_penalty: float = REFERENCE_TRACKER_REWARD_DEFAULTS["crash_penalty"],
    ):
        """Set local command-following reward coefficients."""
        self.pos_error_coef = float(pos_error_coef)
        self.vel_error_coef = float(vel_error_coef)
        self.heading_coef = float(heading_coef)
        self.action_coef = float(action_coef)
        self.action_delta_coef = float(action_delta_coef)
        self.progress_bonus = float(progress_bonus)
        self.semantic_brake_speed_coef = float(semantic_brake_speed_coef)
        self.semantic_slow_speed_coef = float(semantic_slow_speed_coef)
        self.semantic_slow_stop_coef = float(semantic_slow_stop_coef)
        self.semantic_recover_speed_coef = float(semantic_recover_speed_coef)
        self.crash_penalty = float(crash_penalty)

    def coefficients(self) -> dict[str, float]:
        """Return clean v60 reward coefficients for diagnostics."""
        return {
            name: float(getattr(self, name))
            for name in self.COEFFICIENT_NAMES
        }

    def compute(
        self,
        prev_obs: dict[str, Any],
        obs: dict[str, Any],
        reference: ReferenceFrame,
        action_norm: np.ndarray,
        prev_action_norm: np.ndarray,
        *,
        terminated: bool,
        truncated: bool,
    ) -> tuple[float, dict[str, float]]:
        """Compute v60 reward without gate, obstacle, finish, or race terms."""
        pos = np.asarray(obs["pos"], dtype=np.float32)
        prev_pos = np.asarray(prev_obs["pos"], dtype=np.float32)
        vel = np.asarray(obs["vel"], dtype=np.float32)
        pos_error = float(np.linalg.norm(reference.current_point - pos))
        prev_error = float(np.linalg.norm(reference.current_point - prev_pos))
        vel_error = float(np.linalg.norm(reference.desired_velocity - vel))
        heading = safe_normalize(reference.desired_heading)
        current_heading = quat_to_rotmat(np.asarray(obs["quat"], dtype=np.float32))[:, 0]
        current_heading[2] = 0.0
        current_heading = safe_normalize(current_heading)
        heading_error = 1.0 - float(np.clip(np.dot(heading, current_heading), -1.0, 1.0))
        action_penalty = float(np.mean(np.square(action_norm)))
        delta_penalty = float(np.mean(np.square(action_norm - prev_action_norm)))
        semantic_terms = ReferenceTrackerReward._semantic_terms(reference, vel)
        reward = (
            -self.pos_error_coef * pos_error
            - self.vel_error_coef * vel_error
            - self.heading_coef * heading_error
            - self.action_coef * action_penalty
            - self.action_delta_coef * delta_penalty
            + self.progress_bonus * (prev_error - pos_error)
            - self.semantic_brake_speed_coef * semantic_terms["brake_hold_speed_excess"]
            - self.semantic_slow_speed_coef * semantic_terms["slow_through_speed_error"]
            - self.semantic_slow_stop_coef * semantic_terms["slow_through_stop_error"]
            - self.semantic_recover_speed_coef * semantic_terms["recover_speed_error"]
        )
        if terminated and not truncated:
            reward -= self.crash_penalty
        diagnostics = {
            "tracker/pos_error": pos_error,
            "tracker/vel_error": vel_error,
            "tracker/heading_error": heading_error,
            "tracker/action_penalty": action_penalty,
            "tracker/action_delta_penalty": delta_penalty,
            "tracker/waypoint_type_id": float(reference.waypoint_type_id),
            "tracker/stop_signal": float(reference.stop_signal),
            "tracker/brake_mask": float(reference.brake_mask),
            "tracker/slow_through_mask": float(reference.slow_through_mask),
            "tracker/desired_speed_error": semantic_terms["desired_speed_error"],
            "tracker/brake_hold_speed_excess": semantic_terms["brake_hold_speed_excess"],
            "tracker/slow_through_speed_error": semantic_terms["slow_through_speed_error"],
            "tracker/slow_through_stop_error": semantic_terms["slow_through_stop_error"],
            "tracker/recover_speed_error": semantic_terms["recover_speed_error"],
        }
        return float(reward), diagnostics


def tracker_reward_model_for_task(
    task: str,
    reward_coefficients: dict[str, float] | None = None,
) -> ReferenceTrackerReward | ReferenceCommandReward:
    """Return the default reward model for a tracker task."""
    canonical = normalize_tracker_task(task)
    coefficients = reward_coefficients or {}
    if canonical in REFERENCE_COMMAND_TRACKER_TASKS:
        command_coefficients = {
            name: float(coefficients[name])
            for name in ReferenceCommandReward.COEFFICIENT_NAMES
            if name in coefficients
        }
        return ReferenceCommandReward(**command_coefficients)
    return ReferenceTrackerReward(**coefficients)


class ReferenceTrackerEnv(gym.Env):
    """Single-env wrapper for Level3 and v55 tracker-training tasks."""

    metadata = {"render_modes": []}

    def __init__(
        self,
        *,
        config_name: str = "level3.toml",
        task: str = "level3",
        max_episode_steps: int = 500,
        seed: int = -1,
        render: bool = False,
        rp_limit_deg: float = 50.0,
        tracker_env_mode: str = "auto",
        observation_layout: str = "auto",
        reward_coefficients: dict[str, float] | None = None,
        reward_model: ReferenceTrackerReward | ReferenceCommandReward | None = None,
    ):
        """Wrap a race-compatible env as a tracker training task."""
        super().__init__()
        self.config_name = config_name
        self.config = load_config(Path(__file__).parents[2] / "config" / config_name)
        self.task = normalize_tracker_task(task)
        self.tracker_env_mode = tracker_env_mode_from_config(
            self.config,
            self.task,
            tracker_env_mode,
        )
        self.observation_layout = default_tracker_observation_layout(
            self.task,
            observation_layout,
        )
        self.max_episode_steps = int(max_episode_steps)
        self.config.sim.render = bool(render)
        if int(seed) >= 0:
            self.config.env.seed = int(seed)
        self.base_env = gym.make(
            self.config.env.id,
            freq=self.config.env.freq,
            sim_config=self.config.sim,
            sensor_range=self.config.env.sensor_range,
            control_mode=self.config.env.control_mode,
            track=self.config.env.track,
            disturbances=self.config.env.get("disturbances"),
            randomizations=self.config.env.get("randomizations"),
            seed=self.config.env.seed,
            max_episode_steps=self.max_episode_steps,
        )
        self.base_env = JaxToNumpy(self.base_env)
        self.generator = ReferenceTrajectoryGenerator(
            self.task,
            dt=1.0 / float(self.config.env.freq),
        )
        self.observation_builder = ReferenceTrackerObservation(self.observation_layout)
        if reward_model is not None and reward_coefficients is not None:
            raise ValueError("Pass either reward_model or reward_coefficients, not both.")
        self.reward_model = reward_model or tracker_reward_model_for_task(
            self.task,
            reward_coefficients,
        )
        self.action_low, self.action_high = action_bounds_from_config(
            self.config,
            rp_limit_deg,
        )
        self.action_space = spaces.Box(low=-1.0, high=1.0, shape=(4,), dtype=np.float32)
        self.observation_space = spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(self.observation_builder.obs_dim,),
            dtype=np.float32,
        )
        self._raw_obs: dict[str, Any] | None = None
        self._reference: ReferenceFrame | None = None
        self._memory: TrackerMemory | None = None
        self._steps = 0
        self.last_diagnostics: dict[str, float] = {}

    def reset(
        self,
        *,
        seed: int | None = None,
        options: dict[str, Any] | None = None,
    ) -> tuple[np.ndarray, dict[str, Any]]:
        """Reset the wrapped race env and rebuild tracker memory/reference."""
        raw_obs, info = self.base_env.reset(seed=seed, options=options)
        self.generator.reset(raw_obs)
        self._memory = TrackerMemory.from_observation(raw_obs)
        self._reference = self.generator.reference(raw_obs)
        self._raw_obs = raw_obs
        self._steps = 0
        self.last_diagnostics = {}
        return self.observation_builder.build(raw_obs, self._reference, self._memory), info

    def step(self, action: np.ndarray) -> tuple[np.ndarray, float, bool, bool, dict[str, Any]]:
        """Apply one normalized tracker action to the wrapped attitude-control env."""
        if self._raw_obs is None or self._reference is None or self._memory is None:
            raise RuntimeError("ReferenceTrackerEnv.step called before reset.")
        action_norm = np.clip(np.asarray(action, dtype=np.float32), -1.0, 1.0)
        sim_action = scale_action(action_norm, self.action_low, self.action_high)
        prev_obs = self._raw_obs
        prev_action = self._memory.last_action_norm.copy()
        raw_obs, _sparse_reward, terminated, truncated, info = self.base_env.step(sim_action)
        self._steps += 1
        truncated = bool(truncated or self._steps >= self.max_episode_steps)
        reward_obs = self._final_observation(raw_obs, info)
        reward, diagnostics = self.reward_model.compute(
            prev_obs,
            reward_obs,
            self._reference,
            action_norm,
            prev_action,
            terminated=bool(terminated),
            truncated=bool(truncated),
        )
        self._memory.update(reward_obs, action_norm)
        self._reference = self.generator.reference(reward_obs)
        self._raw_obs = reward_obs
        self.last_diagnostics = diagnostics | {
            "tracker/phase_id": float(self._reference.phase_id),
            "tracker/target_gate": float(self._reference.target_gate),
            "tracker/reward": float(reward),
        }
        observation = self.observation_builder.build(reward_obs, self._reference, self._memory)
        return observation, float(reward), bool(terminated), bool(truncated), info

    def close(self) -> None:
        """Close the wrapped environment."""
        self.base_env.close()

    @staticmethod
    def _final_observation(raw_obs: dict[str, Any], info: dict[str, Any]) -> dict[str, Any]:
        if isinstance(info, dict) and "final_observation" in info:
            final_obs = info["final_observation"]
            if isinstance(final_obs, dict):
                return final_obs
        if isinstance(info, dict) and "reset_observations" in info:
            reset_obs = info["reset_observations"]
            if isinstance(reset_obs, dict):
                return reset_obs
        return raw_obs


class ReferenceTrackerVectorEnv:
    """Vectorized tracker-training wrapper over Gymnasium's JAX vector env."""

    def __init__(
        self,
        *,
        config_name: str = "level3.toml",
        task: str = "level3",
        num_envs: int = 1,
        max_episode_steps: int = 500,
        seed: int = -1,
        render: bool = False,
        rp_limit_deg: float = 50.0,
        tracker_env_mode: str = "auto",
        observation_layout: str = "auto",
        reward_coefficients: dict[str, float] | None = None,
        reward_model: ReferenceTrackerReward | ReferenceCommandReward | None = None,
        jax_device: str = "gpu",
    ):
        """Wrap a vector race env as parallel tracker-training worlds."""
        self.num_envs = int(num_envs)
        if self.num_envs < 1:
            raise ValueError("num_envs must be >= 1")
        self.config_name = config_name
        self.config = load_config(Path(__file__).parents[2] / "config" / config_name)
        self.task = normalize_tracker_task(task)
        self.tracker_env_mode = tracker_env_mode_from_config(
            self.config,
            self.task,
            tracker_env_mode,
        )
        self.observation_layout = default_tracker_observation_layout(
            self.task,
            observation_layout,
        )
        self.config.sim.render = bool(render)
        if int(seed) >= 0:
            self.config.env.seed = int(seed)
        self._jax_device = jax.devices(jax_device)[0]
        self.base_env = gym.make_vec(
            self.config.env.id,
            num_envs=self.num_envs,
            freq=self.config.env.freq,
            sim_config=self.config.sim,
            sensor_range=self.config.env.sensor_range,
            control_mode=self.config.env.control_mode,
            track=self.config.env.track,
            disturbances=self.config.env.get("disturbances"),
            randomizations=self.config.env.get("randomizations"),
            seed=self.config.env.seed,
            max_episode_steps=int(max_episode_steps),
            device=jax_device,
        )
        self.generators = [
            ReferenceTrajectoryGenerator(self.task, dt=1.0 / float(self.config.env.freq))
            for _ in range(self.num_envs)
        ]
        self.observation_builder = ReferenceTrackerObservation(self.observation_layout)
        if reward_model is not None and reward_coefficients is not None:
            raise ValueError("Pass either reward_model or reward_coefficients, not both.")
        self.reward_model = reward_model or tracker_reward_model_for_task(
            self.task,
            reward_coefficients,
        )
        self.max_episode_steps = int(max_episode_steps)
        self.action_low, self.action_high = action_bounds_from_config(
            self.config,
            rp_limit_deg,
        )
        self.single_action_space = spaces.Box(
            low=-1.0,
            high=1.0,
            shape=(4,),
            dtype=np.float32,
        )
        self.single_observation_space = spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(self.observation_builder.obs_dim,),
            dtype=np.float32,
        )
        self.action_space = batch_space(self.single_action_space, self.num_envs)
        self.observation_space = batch_space(
            self.single_observation_space,
            self.num_envs,
        )
        self._raw_obs: dict[str, Any] | None = None
        self._references: list[ReferenceFrame | None] = [None] * self.num_envs
        self._memories: list[TrackerMemory | None] = [None] * self.num_envs
        self._steps = np.zeros(self.num_envs, dtype=np.int32)
        self.last_diagnostics: dict[str, float] = {}

    def reset(
        self,
        *,
        seed: int | None = None,
        options: dict[str, Any] | None = None,
    ) -> tuple[np.ndarray, dict[str, Any]]:
        """Reset all vector worlds and rebuild per-world tracker state."""
        raw_obs, info = self.base_env.reset(seed=seed, options=options)
        raw_obs = _to_numpy_tree(raw_obs)
        info = _to_numpy_tree(info)
        rows = []
        for env_idx in range(self.num_envs):
            obs_i = _tree_index(raw_obs, env_idx)
            self.generators[env_idx].reset(obs_i)
            memory = TrackerMemory.from_observation(obs_i)
            reference = self.generators[env_idx].reference(obs_i)
            self._memories[env_idx] = memory
            self._references[env_idx] = reference
            rows.append(self.observation_builder.build(obs_i, reference, memory))
        self._raw_obs = raw_obs
        self._steps = np.zeros(self.num_envs, dtype=np.int32)
        self.last_diagnostics = {}
        return np.stack(rows).astype(np.float32), info

    def step(
        self,
        actions: np.ndarray,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, dict[str, Any]]:
        """Apply one normalized tracker action per world."""
        if self._raw_obs is None:
            raise RuntimeError("ReferenceTrackerVectorEnv.step called before reset.")
        action_norm = np.clip(np.asarray(actions, dtype=np.float32), -1.0, 1.0)
        if action_norm.shape != (self.num_envs, 4):
            raise ValueError(
                f"Expected actions shape {(self.num_envs, 4)}, got {action_norm.shape}"
            )
        sim_action = scale_action(action_norm, self.action_low, self.action_high)
        prev_obs_batch = self._raw_obs
        raw_obs, _sparse_reward, terminated, truncated, info = self.base_env.step(
            jax.device_put(sim_action, self._jax_device)
        )
        raw_obs = _to_numpy_tree(raw_obs)
        info = _to_numpy_tree(info)
        terminations = np.asarray(terminated, dtype=bool).reshape(self.num_envs)
        truncations = np.asarray(truncated, dtype=bool).reshape(self.num_envs)
        self._steps += 1
        truncations = truncations | (self._steps >= self.max_episode_steps)

        rewards = np.zeros(self.num_envs, dtype=np.float32)
        obs_rows = []
        diagnostics_rows: list[dict[str, float]] = []
        for env_idx in range(self.num_envs):
            memory = self._memories[env_idx]
            reference = self._references[env_idx]
            if memory is None or reference is None:
                raise RuntimeError("ReferenceTrackerVectorEnv internal state is uninitialized.")
            prev_obs = _tree_index(prev_obs_batch, env_idx)
            final_obs = self._final_observation(raw_obs, info, env_idx)
            next_obs = _tree_index(raw_obs, env_idx)
            prev_action = memory.last_action_norm.copy()
            reward, diagnostics = self.reward_model.compute(
                prev_obs,
                final_obs,
                reference,
                action_norm[env_idx],
                prev_action,
                terminated=bool(terminations[env_idx]),
                truncated=bool(truncations[env_idx]),
            )
            rewards[env_idx] = float(reward)
            done = bool(terminations[env_idx] or truncations[env_idx])
            if done:
                self.generators[env_idx].reset(next_obs)
                memory = TrackerMemory.from_observation(next_obs)
                self._steps[env_idx] = 0
            else:
                memory.update(final_obs, action_norm[env_idx])
            reference = self.generators[env_idx].reference(next_obs)
            self._memories[env_idx] = memory
            self._references[env_idx] = reference
            row_diagnostics = diagnostics | {
                "tracker/phase_id": float(reference.phase_id),
                "tracker/target_gate": float(reference.target_gate),
                "tracker/reward": float(reward),
            }
            diagnostics_rows.append(row_diagnostics)
            obs_rows.append(self.observation_builder.build(next_obs, reference, memory))

        self._raw_obs = raw_obs
        self.last_diagnostics = _mean_diagnostics(diagnostics_rows)
        return (
            np.stack(obs_rows).astype(np.float32),
            rewards,
            terminations.astype(bool),
            truncations.astype(bool),
            info,
        )

    def close(self) -> None:
        """Close the wrapped vector environment."""
        self.base_env.close()

    @staticmethod
    def _final_observation(
        raw_obs: dict[str, Any],
        info: dict[str, Any],
        env_idx: int,
    ) -> dict[str, Any]:
        if isinstance(info, dict) and "final_observation" in info:
            final_obs = info["final_observation"]
            if isinstance(final_obs, dict):
                return _tree_index(final_obs, env_idx)
        if isinstance(info, dict) and "reset_observations" in info:
            reset_obs = info["reset_observations"]
            if isinstance(reset_obs, dict):
                return _tree_index(reset_obs, env_idx)
        return _tree_index(raw_obs, env_idx)
